"""
Weekly cron: generate fresh MCQ question variants for both tracks.
Tradr questions use real yfinance + news data woven into the context.
Codr questions are fresh DSA/pattern variants generated by Claude.
Stored in Supabase `questions` table; lessons draw from this pool.
"""

import asyncio
import hashlib
import json
import logging
from datetime import date, datetime, timezone

logger = logging.getLogger(__name__)

# ─── Topic pools ──────────────────────────────────────────────────────────────

_TRADR_TOPICS: dict[str, list[str]] = {
    "india": [
        "RBI monetary policy and its effect on banking stocks",
        "FII vs DII flows and their impact on the Nifty",
        "Reading an Indian company earnings report (EPS, guidance)",
        "SEBI regulation and its effect on F&O markets",
        "Inflation (CPI) and its impact on bond yields",
        "Nifty 50 sector composition and rotation",
        "Currency (rupee) and its relationship to FII flows",
    ],
    "us": [
        "Fed monetary policy and its effect on the S&P 500",
        "US CPI data and Treasury yield movement",
        "Tech earnings season — beats, misses, guidance",
        "NASDAQ vs S&P 500 — when they diverge and why",
        "Non-farm payrolls and labour market data",
        "Dollar strength and its impact on US multinationals",
    ],
    "eu": [
        "ECB rate decisions and the euro exchange rate",
        "DAX composition — Germany's export-heavy economy",
        "PMI data and manufacturing sector moves",
        "European luxury goods and China demand correlation",
        "EUR/USD moves and their market implications",
    ],
}

_CODR_TOPICS: list[str] = [
    "Two Pointers — opposite ends approach",
    "Two Pointers — fast and slow pointer (Floyd's algorithm)",
    "Sliding Window — fixed size",
    "Sliding Window — variable size",
    "Binary Search — standard sorted array",
    "Binary Search — rotated array",
    "BFS — shortest path in unweighted graph",
    "DFS — recursive tree traversal",
    "HashMap — frequency counting and two-sum variants",
    "Stack — monotonic stack applications",
    "Big O complexity analysis",
    "Identifying edge cases in algorithm problems",
]


# ─── Context builders ─────────────────────────────────────────────────────────

async def _tradr_context(market: str) -> str:
    from services.market_service import get_quote
    from services.news_service import get_headlines

    tickers = {
        "india": [("^NSEI", "Nifty 50"), ("^BSESN", "Sensex"), ("^NSEBANK", "Bank Nifty")],
        "us":    [("^GSPC", "S&P 500"), ("^IXIC", "NASDAQ"), ("^DJI", "Dow Jones")],
        "eu":    [("^GDAXI", "DAX"), ("^FCHI", "CAC 40")],
    }.get(market, [])

    moves: list[str] = []
    for ticker, name in tickers:
        try:
            q = await asyncio.to_thread(get_quote, ticker)
            d = "up" if q["change_pct"] >= 0 else "down"
            moves.append(f"{name} {d} {abs(q['change_pct']):.1f}% at {q['price']:.0f}")
        except Exception:
            pass

    headlines = await get_headlines(market, page_size=3)
    hl = "; ".join(h["title"] for h in headlines[:3]) if headlines else "no headlines"
    lines = [f"Date: {date.today().isoformat()}"]
    if moves:
        lines.append("Markets today: " + ", ".join(moves))
    lines.append(f"News: {hl}")
    return "\n".join(lines)


# ─── Builders ────────────────────────────────────────────────────────────────

async def build_tradr_questions(market: str, count: int = 5) -> list[dict]:
    from services.claude_service import generate_question_variant
    context = await _tradr_context(market)
    topics = _TRADR_TOPICS.get(market, _TRADR_TOPICS["india"])
    results: list[dict] = []

    for i in range(count):
        topic = topics[i % len(topics)]
        difficulty = (i % 3) + 2
        try:
            data = await generate_question_variant(
                track="tradr",
                topic=topic,
                market_context=context,
                difficulty=difficulty,
            )
            seed = f"tradr-{market}-{date.today().isoformat()}-{i}"
            results.append({
                "id":                hashlib.md5(seed.encode()).hexdigest()[:12],
                "lesson_id":         f"live-{market}-{i % len(topics)}",
                "track":             "tradr",
                "market":            market,
                "type":              "mcq",
                "question":          data["question"],
                "options":           json.dumps(data["options"]),
                "correct":           data["correct"],
                "explanation_short": data.get("explanation_short", ""),
                "tags":              data.get("tags", []),
                "difficulty":        difficulty,
                "active":            True,
                "generated_at":      datetime.now(timezone.utc).isoformat(),
            })
        except Exception as exc:
            logger.error("Tradr question build failed (%s, i=%d): %s", market, i, exc)

    return results


async def build_codr_questions(count: int = 8) -> list[dict]:
    from services.claude_service import generate_question_variant
    results: list[dict] = []

    for i in range(count):
        topic = _CODR_TOPICS[i % len(_CODR_TOPICS)]
        difficulty = (i % 3) + 2
        try:
            data = await generate_question_variant(
                track="codr",
                topic=topic,
                market_context="",
                difficulty=difficulty,
            )
            seed = f"codr-{date.today().isoformat()}-{i}"
            results.append({
                "id":                hashlib.md5(seed.encode()).hexdigest()[:12],
                "lesson_id":         f"live-codr-{i % len(_CODR_TOPICS)}",
                "track":             "codr",
                "market":            None,
                "type":              "mcq",
                "question":          data["question"],
                "options":           json.dumps(data["options"]),
                "correct":           data["correct"],
                "explanation_short": data.get("explanation_short", ""),
                "tags":              data.get("tags", []),
                "difficulty":        difficulty,
                "active":            True,
                "generated_at":      datetime.now(timezone.utc).isoformat(),
            })
        except Exception as exc:
            logger.error("Codr question build failed (i=%d): %s", i, exc)

    return results


async def store_questions(questions: list[dict]) -> None:
    from database.supabase_client import get_client
    if not questions:
        return
    db = get_client()
    db.table("questions").upsert(questions).execute()
    logger.info("Stored %d questions in Supabase", len(questions))


async def run_weekly_question_build() -> None:
    """Entry point called by APScheduler alongside the scenario build."""
    logger.info("Weekly question build starting")
    all_questions: list[dict] = []

    for market in ("india", "us", "eu"):
        try:
            qs = await build_tradr_questions(market, count=5)
            all_questions.extend(qs)
        except Exception as exc:
            logger.error("Tradr question build failed for %s: %s", market, exc)

    try:
        qs = await build_codr_questions(count=8)
        all_questions.extend(qs)
    except Exception as exc:
        logger.error("Codr question build failed: %s", exc)

    await store_questions(all_questions)
    logger.info("Weekly question build complete — %d questions stored", len(all_questions))
