import type { Lesson } from '../types';

const CODR_LESSONS_2: Lesson[] = [

  // ─── UNIT 4: Binary Search ────────────────────────────────────────────────────

  {
    id: 'codr4-lesson1', name: 'Binary Search Fundamentals', unit: 4, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr4-lesson1-q1', type: 'multiple_choice',
        question: 'What is the key precondition for binary search to work correctly?',
        options: ['The array must contain unique elements', 'The array must be sorted', 'The array length must be a power of 2', 'The target must be in the array'],
        correct: 1,
        explanationShort: 'Binary search works by halving the search space. Halving only makes sense when the array is sorted — smaller values left, larger right.',
        tags: ['binary_search', 'fundamentals'],
      },
      {
        id: 'codr4-lesson1-q2', type: 'multiple_choice',
        question: 'Time complexity of binary search on a sorted array of n elements:',
        options: ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'],
        correct: 2,
        explanationShort: 'Each step halves the remaining search space. Starting from n, you can halve at most log₂(n) times.',
        tags: ['binary_search', 'complexity'],
      },
      {
        id: 'codr4-lesson1-q3', type: 'multiple_choice',
        question: 'Why prefer `mid = left + (right - left) // 2` over `mid = (left + right) // 2`?',
        codeSnippet: '# Option A (common but risky):\nmid = (left + right) // 2\n\n# Option B (always safe):\nmid = left + (right - left) // 2',
        codeLanguage: 'python',
        options: [
          'It\'s faster to compute',
          'It avoids integer overflow when left + right exceeds the max int value',
          'It always finds the leftmost occurrence',
          'It works on unsorted arrays',
        ],
        correct: 1,
        explanationShort: 'In Python overflow isn\'t an issue, but in Java/C++ (32-bit int), left + right can overflow. The safe form is always correct.',
        tags: ['binary_search', 'overflow'],
      },
      {
        id: 'codr4-lesson1-q4', type: 'multiple_choice',
        question: 'The standard template: target < `nums[mid]`. Which line runs next?',
        arrayData: {
          title: 'SORTED ARRAY — target = 6, mid points at 9',
          elements: [
            { value: 1,  highlight: 'inactive' },
            { value: 3,  highlight: 'inactive' },
            { value: 5,  highlight: 'inactive' },
            { value: 9,  highlight: 'secondary', pointer: 'mid'   },
            { value: 12, highlight: 'inactive' },
            { value: 15, highlight: 'inactive' },
          ],
        },
        codeSnippet: 'left, right = 0, len(nums) - 1\nwhile left <= right:\n    mid = left + (right - left) // 2\n    if nums[mid] == target:\n        return mid\n    elif nums[mid] < target:\n        left = mid + 1\n    else:\n        ???  # target < nums[mid]',
        codeLanguage: 'python',
        options: ['right = mid + 1', 'left = mid + 1', 'right = mid - 1', 'left = mid - 1'],
        correct: 2,
        explanationShort: 'The target is in the left half. Discard mid and everything to its right: right = mid - 1.',
        tags: ['binary_search', 'fundamentals'],
      },
    ],
  },

  {
    id: 'codr4-lesson2', name: 'Search in Rotated Array', unit: 4, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr4-lesson2-q1', type: 'multiple_choice',
        question: '[4,5,6,7,0,1,2] is rotated sorted. What is always true when you pick mid?',
        options: [
          'Neither half is ever sorted',
          'At least one of the two halves is always sorted',
          'Both halves are always sorted',
          'The half without mid is always sorted',
        ],
        correct: 1,
        explanationShort: 'Rotation creates one "clean" sorted half and one "broken" half. Binary search works by identifying which is which.',
        tags: ['binary_search', 'rotated_array'],
      },
      {
        id: 'codr4-lesson2-q2', type: 'multiple_choice',
        question: 'In a rotated sorted array, how do you check if the LEFT half is sorted?',
        codeSnippet: 'if ???:          # left half is sorted\n    # target in [nums[left], nums[mid]]?\nelse:             # right half is sorted\n    # target in [nums[mid], nums[right]]?',
        codeLanguage: 'python',
        options: [
          'Compare nums[mid] with the target',
          'Check if nums[left] <= nums[mid]',
          'Check if nums[mid] < nums[right]',
          'Check if mid < n/2',
        ],
        correct: 1,
        explanationShort: 'If nums[left] ≤ nums[mid], the left segment is the clean sorted half. Otherwise, the right half is sorted.',
        tags: ['binary_search', 'rotated_array'],
      },
      {
        id: 'codr4-lesson2-q3', type: 'multiple_choice',
        question: 'Time complexity of searching a rotated sorted array:',
        options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(log²n)'],
        correct: 1,
        explanationShort: 'We still halve the search space each step — the rotation only adds one comparison to decide which half is clean.',
        tags: ['binary_search', 'rotated_array', 'complexity'],
      },
      {
        id: 'codr4-lesson2-q4', type: 'multiple_choice',
        question: 'Array [4,5,6,7,0,1,2], target=0. Left=0, right=6, mid=3, nums[mid]=7. Left half [4,5,6,7] is sorted. Target 0 is NOT in [4,7]. Next step?',
        options: ['Search left half [4,5,6]', 'Search right half [0,1,2]', 'Return mid=3', 'Sort and restart'],
        correct: 1,
        explanationShort: '0 is outside [4,7], so it can\'t be in the left half. Search right: left = mid + 1 = 4.',
        tags: ['binary_search', 'rotated_array'],
      },
    ],
  },

  {
    id: 'codr4-lesson3', name: 'Finding Boundaries', unit: 4, market: 'shared', xpReward: 30,
    questions: [
      {
        id: 'codr4-lesson3-q1', type: 'multiple_choice',
        question: '"Find leftmost position of target in sorted array with duplicates." What modification finds the left boundary?',
        options: [
          'Return mid as soon as nums[mid] == target',
          'When nums[mid] == target, keep searching left: right = mid',
          'Use two binary searches and take the minimum',
          'Switch to linear scan when duplicates are found',
        ],
        correct: 1,
        explanationShort: 'Don\'t stop on the first match — set right = mid and keep going. The loop converges to the leftmost occurrence.',
        tags: ['binary_search', 'boundaries'],
      },
      {
        id: 'codr4-lesson3-q2', type: 'multiple_choice',
        question: '"Upper bound" in binary search means:',
        options: [
          'The last index where target appears',
          'The first index where an element is strictly greater than target',
          'The maximum element in the array',
          'Return -1 if target is absent',
        ],
        correct: 1,
        explanationShort: 'Upper bound is the insertion point for target+1. All elements to its left are ≤ target.',
        tags: ['binary_search', 'boundaries'],
      },
      {
        id: 'codr4-lesson3-q3', type: 'multiple_choice',
        question: '"Binary search on the answer" is used when:',
        options: [
          'The input array must be sorted first',
          'The answer lies in a range where feasibility is monotonic — if X works, X+1 also works',
          'The array has no duplicates',
          'The target is guaranteed to exist',
        ],
        correct: 1,
        explanationShort: 'If you can check "is X feasible?" and feasibility is monotonic, binary search the answer space instead of the array.',
        tags: ['binary_search', 'answer_space'],
      },
      {
        id: 'codr4-lesson3-q4', type: 'multiple_choice',
        question: '"Min days to make m bouquets" — you binary search on:',
        options: [
          'The array of bloom days directly',
          'The number of days (from min bloom day to max bloom day)',
          'The number of bouquets m',
          'The sorted indices of bloom days',
        ],
        correct: 1,
        explanationShort: 'The answer is a number of days. More days → easier to make bouquets (monotonic). Binary search [min, max] of bloom days.',
        tags: ['binary_search', 'answer_space'],
      },
    ],
  },

  {
    id: 'codr4-quiz', name: 'Unit 4 Quiz', unit: 4, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr4-quiz-q1', type: 'multiple_choice',
        question: 'Classic bug: `right = len(nums)` instead of `len(nums) - 1`. What goes wrong?',
        options: [
          'The loop runs one extra iteration harmlessly',
          'nums[mid] can access an out-of-bounds index when mid reaches len(nums)',
          'The function never returns -1',
          'It only works for even-length arrays',
        ],
        correct: 1,
        explanationShort: 'If right starts out of bounds and mid ever equals it, nums[mid] throws an IndexError. Always: right = len(nums) - 1.',
        tags: ['binary_search', 'bugs'],
      },
      {
        id: 'codr4-quiz-q2', type: 'multiple_choice',
        question: 'Binary searching [1,3,5,5,5,7,9] for target=5 with `right = mid` on match returns:',
        options: ['Last occurrence (index 4)', 'Any occurrence', 'First occurrence (index 2)', '-1 if duplicates exist'],
        correct: 2,
        explanationShort: 'Setting right = mid on match keeps searching left. The loop converges to the leftmost 5 at index 2.',
        tags: ['binary_search', 'boundaries'],
      },
      {
        id: 'codr4-quiz-q3', type: 'multiple_choice',
        question: 'Time complexity of finding BOTH first and last occurrence of a target in a sorted array:',
        options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(log²n)'],
        correct: 1,
        explanationShort: 'Two independent binary searches, each O(log n). Total is still O(log n).',
        tags: ['binary_search', 'complexity'],
      },
      {
        id: 'codr4-quiz-q4', type: 'multiple_choice',
        question: 'Array [3,4,5,1,2], target=1. Left half [3,4,5] is sorted. 1 is NOT in [3,5]. You:',
        options: ['Return -1', 'Search left half anyway', 'Search right half [1,2]', 'Sort and restart'],
        correct: 2,
        explanationShort: '1 is outside [3,5], so it must be in the other half. Set left = mid + 1 and search [1,2].',
        tags: ['binary_search', 'rotated_array'],
      },
      {
        id: 'codr4-quiz-q5', type: 'multiple_choice',
        question: '"Min ship capacity to carry packages in D days" — you binary search on:',
        options: [
          'The number of packages',
          'The number of days D',
          'The capacity — from max single package weight to total sum of all weights',
          'The sorted package weights',
        ],
        correct: 2,
        explanationShort: 'Capacity is the answer. Lower bound: must carry heaviest package. Upper bound: carry everything in one day.',
        tags: ['binary_search', 'answer_space'],
      },
    ],
  },

  // ─── UNIT 5: Trees & Recursion ────────────────────────────────────────────────

  {
    id: 'codr5-lesson1', name: 'Binary Tree Traversal', unit: 5, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr5-lesson1-q1', type: 'multiple_choice',
        question: 'In-order traversal of a Binary Search Tree visits nodes in what order?',
        treeData: {
          title: 'BST — what order does in-order visit these nodes?',
          root: {
            value: 4,
            left: {
              value: 2,
              left:  { value: 1, highlight: 'visited' },
              right: { value: 3, highlight: 'visited' },
              highlight: 'visited',
            },
            right: {
              value: 6,
              left:  { value: 5 },
              right: { value: 7 },
            },
            highlight: 'visited',
          },
        },
        options: ['Random order', 'Root, left subtree, right subtree', 'Ascending sorted order', 'Descending sorted order'],
        correct: 2,
        explanationShort: 'In-order = left → root → right. In a BST (left < root < right), this always produces ascending order.',
        tags: ['tree', 'traversal', 'inorder'],
      },
      {
        id: 'codr5-lesson1-q2', type: 'multiple_choice',
        question: 'Which traversal visits the root FIRST?',
        options: ['In-order (left, root, right)', 'Post-order (left, right, root)', 'Pre-order (root, left, right)', 'Level-order (BFS)'],
        correct: 2,
        explanationShort: 'Pre-order processes root first, then recursively the left and right subtrees. Useful for tree serialisation.',
        tags: ['tree', 'traversal', 'preorder'],
      },
      {
        id: 'codr5-lesson1-q3', type: 'multiple_choice',
        question: 'You need to delete an entire tree. Which traversal ensures children are deleted before their parent?',
        options: ['Pre-order', 'In-order', 'Post-order', 'Level-order'],
        correct: 2,
        explanationShort: 'Post-order = left → right → root. You free children first, so the parent is the last thing deleted — safe.',
        tags: ['tree', 'traversal', 'postorder'],
      },
      {
        id: 'codr5-lesson1-q4', type: 'multiple_choice',
        question: 'Space complexity of recursive in-order traversal on a balanced tree of height h:',
        options: ['O(1)', 'O(h) — the call stack depth equals tree height', 'O(n)', 'O(n log n)'],
        correct: 1,
        explanationShort: 'Each recursive call adds one frame. The deepest recursion goes h levels — call stack is O(h). For balanced trees h = O(log n).',
        tags: ['tree', 'traversal', 'complexity'],
      },
      {
        id: 'codr5-lesson1-q5', type: 'multiple_choice',
        question: 'Level-order traversal uses which data structure?',
        options: ['Stack', 'Queue', 'Hash map', 'Priority queue'],
        correct: 1,
        explanationShort: 'Level-order = BFS. A queue ensures nodes are processed in the order they were added — level by level.',
        tags: ['tree', 'traversal', 'bfs'],
      },
    ],
  },

  {
    id: 'codr5-lesson2', name: 'DFS on Trees', unit: 5, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr5-lesson2-q1', type: 'multiple_choice',
        question: 'Recursive DFS on a binary tree — what is the base case?',
        options: [
          'When the current node has two children',
          'When the current node is the root',
          'When the current node is null',
          'When left and right subtrees are equal in size',
        ],
        correct: 2,
        explanationShort: 'A null node means we\'ve gone past a leaf. Return 0 (depth), False (path check), or similar — the recursion unwinds from here.',
        tags: ['tree', 'dfs', 'recursion'],
      },
      {
        id: 'codr5-lesson2-q2', type: 'multiple_choice',
        question: 'Finding max depth of a binary tree with DFS — what do you return at each node?',
        treeData: {
          title: 'TREE — what is the max depth?',
          root: {
            value: 1,
            highlight: 'primary',
            left: {
              value: 2,
              left:  { value: 4, highlight: 'visited' },
              right: { value: 5, highlight: 'visited' },
            },
            right: { value: 3 },
          },
        },
        options: [
          '1 + depth of left subtree only',
          '1 + max(depth of left, depth of right)',
          'depth of left + depth of right',
          '1 if the node has no children, 0 otherwise',
        ],
        correct: 1,
        explanationShort: 'The deeper subtree determines the height. Add 1 for the current node: 1 + max(dfs(left), dfs(right)).',
        tags: ['tree', 'dfs', 'max_depth'],
      },
      {
        id: 'codr5-lesson2-q3', type: 'multiple_choice',
        question: '"Path Sum" — does a root-to-leaf path exist summing to target? Which DFS approach?',
        options: [
          'BFS — explore all levels first',
          'DFS — subtract current node value from target, check if leaf and target == 0',
          'Sort nodes by value then search',
          'Build prefix sums for all root-to-leaf paths',
        ],
        correct: 1,
        explanationShort: 'Pass remaining = target - node.val down. At a leaf: if remaining == 0, path found. DFS naturally traces root-to-leaf paths.',
        tags: ['tree', 'dfs', 'path_sum'],
      },
      {
        id: 'codr5-lesson2-q4', type: 'multiple_choice',
        question: 'Time complexity of DFS on a binary tree with n nodes:',
        options: ['O(log n)', 'O(h) — only one path', 'O(n)', 'O(n²)'],
        correct: 2,
        explanationShort: 'DFS visits every node exactly once — O(n). Even though it goes deep first, it backtracks and covers the whole tree.',
        tags: ['tree', 'dfs', 'complexity'],
      },
    ],
  },

  {
    id: 'codr5-lesson3', name: 'BFS & Level Order', unit: 5, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr5-lesson3-q1', type: 'multiple_choice',
        question: 'BFS on a binary tree — what do you add to the queue first?',
        treeData: {
          title: 'TREE — BFS starts here',
          root: {
            value: 1,
            highlight: 'primary',
            left: {
              value: 2,
              left:  { value: 4 },
              right: { value: 5 },
            },
            right: {
              value: 3,
              right: { value: 6 },
            },
          },
        },
        options: ['The left-most leaf', 'The root', 'All leaves simultaneously', 'The deepest node'],
        correct: 1,
        explanationShort: 'BFS starts at the root (level 0) and expands outward. The root is the only node at level 0.',
        tags: ['tree', 'bfs', 'level_order'],
      },
      {
        id: 'codr5-lesson3-q2', type: 'multiple_choice',
        question: 'To collect each level\'s nodes as a separate list, what do you track at the start of each level?',
        options: [
          'The depth of each node individually',
          'The queue size at the start of each level — process exactly that many nodes',
          'The left and right boundaries of each level',
          'The maximum value at each level',
        ],
        correct: 1,
        explanationShort: 'Snapshot len(queue) before processing a level. That many dequeues = one full level. Children enqueued during this are the next level.',
        tags: ['tree', 'bfs', 'level_order'],
      },
      {
        id: 'codr5-lesson3-q3', type: 'multiple_choice',
        question: 'BFS guarantees shortest path in which type of graph?',
        options: ['Weighted directed graph', 'Unweighted graph', 'Negative-weight graph', 'DAG only'],
        correct: 1,
        explanationShort: 'BFS explores distance 1, then 2, then 3. In an unweighted graph, the first time BFS reaches a node is via the shortest path.',
        tags: ['bfs', 'shortest_path'],
      },
      {
        id: 'codr5-lesson3-q4', type: 'multiple_choice',
        question: 'Worst-case space complexity of BFS on a binary tree:',
        options: ['O(log n)', 'O(h)', 'O(n)', 'O(1)'],
        correct: 2,
        explanationShort: 'The last level of a complete binary tree holds ~n/2 nodes. All fit in the queue at once — O(n) space.',
        tags: ['tree', 'bfs', 'complexity'],
      },
    ],
  },

  {
    id: 'codr5-lesson4', name: 'Binary Search Tree', unit: 5, market: 'shared', xpReward: 30,
    questions: [
      {
        id: 'codr5-lesson4-q1', type: 'multiple_choice',
        question: 'In a valid BST, what must be true for EVERY node (not just direct children)?',
        treeData: {
          title: 'VALID BST — the rule applies to every node',
          root: {
            value: 8,
            highlight: 'primary',
            left: {
              value: 3,
              left:  { value: 1, highlight: 'visited' },
              right: { value: 6, highlight: 'visited' },
            },
            right: {
              value: 10,
              right: { value: 14, highlight: 'visited' },
            },
          },
        },
        options: [
          'Left child < node < right child',
          'All nodes in left subtree < node AND all nodes in right subtree > node',
          'Only the direct children satisfy the BST property',
          'The tree must be balanced',
        ],
        correct: 1,
        explanationShort: 'The BST property is recursive. It\'s not enough for direct children — every descendant in the left subtree must be smaller.',
        tags: ['bst', 'fundamentals'],
      },
      {
        id: 'codr5-lesson4-q2', type: 'multiple_choice',
        question: 'Time complexity of search in a BALANCED BST:',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correct: 1,
        explanationShort: 'Each comparison eliminates half the tree. A balanced BST of n nodes has height O(log n).',
        tags: ['bst', 'complexity'],
      },
      {
        id: 'codr5-lesson4-q3', type: 'multiple_choice',
        question: 'Time complexity of search in a WORST-CASE (skewed) BST:',
        options: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'],
        correct: 1,
        explanationShort: 'Inserting sorted data into a BST produces a linked list. Search must traverse all n nodes — O(n). This is why AVL/Red-Black trees exist.',
        tags: ['bst', 'complexity'],
      },
      {
        id: 'codr5-lesson4-q4', type: 'multiple_choice',
        question: 'To validate a BST, why pass bounds [min, max] rather than just comparing to the parent?',
        options: [
          'It\'s faster to compute',
          'A node must satisfy the BST constraint for ALL ancestors, not just the parent',
          'Parent comparison is always sufficient',
          'It handles duplicate values better',
        ],
        correct: 1,
        explanationShort: 'Classic trap: a right subtree node that is larger than its parent but smaller than its grandparent — passes parent check, fails global BST rule.',
        tags: ['bst', 'validation'],
      },
    ],
  },

  {
    id: 'codr5-quiz', name: 'Unit 5 Quiz', unit: 5, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr5-quiz-q1', type: 'multiple_choice',
        question: 'In-order traversal of a BST gives [1,2,3,4,5]. This proves:',
        options: ['The tree is balanced', 'The tree is a valid BST', 'The root is 3', 'All nodes are in the left subtree'],
        correct: 1,
        explanationShort: 'A BST\'s in-order traversal always gives sorted ascending output — and vice versa. It tells us nothing about balance.',
        tags: ['bst', 'traversal'],
      },
      {
        id: 'codr5-quiz-q2', type: 'multiple_choice',
        question: 'Max depth of a binary tree with n nodes in the WORST case (skewed):',
        options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(n²)'],
        correct: 1,
        explanationShort: 'A skewed tree is a linked list. Depth = n. A balanced tree has depth O(log n). BSTs can degrade to skewed without balancing.',
        tags: ['tree', 'depth', 'complexity'],
      },
      {
        id: 'codr5-quiz-q3', type: 'multiple_choice',
        question: 'Which traversal lets you fully reconstruct a binary tree from its output (given null markers)?',
        options: [
          'In-order alone — insufficient',
          'Pre-order with null markers',
          'Post-order alone — root is ambiguous',
          'Level-order without null markers',
        ],
        correct: 1,
        explanationShort: 'Pre-order (root first) + null markers uniquely reconstructs the tree. In-order alone is ambiguous without shape information.',
        tags: ['tree', 'serialisation'],
      },
      {
        id: 'codr5-quiz-q4', type: 'multiple_choice',
        question: 'BFS vs DFS for "does a path exist between A and B in an unweighted graph"?',
        options: [
          'Only BFS — DFS misses edges',
          'Only DFS — BFS is too slow',
          'Both work correctly; BFS finds the shortest path, DFS may use less memory on sparse graphs',
          'Neither — use Dijkstra\'s',
        ],
        correct: 2,
        explanationShort: 'Both visit all reachable nodes. BFS finds shortest path. DFS has O(h) call stack vs BFS O(width) queue — trade-off depends on the graph.',
        tags: ['bfs', 'dfs', 'graphs'],
      },
      {
        id: 'codr5-quiz-q5', type: 'multiple_choice',
        question: 'Height of a BALANCED binary tree with n nodes:',
        options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
        correct: 1,
        explanationShort: 'Doubling nodes adds one level. n nodes → height ≈ log₂(n). This is why balanced trees are so efficient.',
        tags: ['tree', 'height', 'complexity'],
      },
      {
        id: 'codr5-quiz-q6', type: 'multiple_choice',
        question: 'Finding LCA (Lowest Common Ancestor) in a BST: both target nodes are less than root. You:',
        options: ['LCA is the root', 'Search right subtree', 'Search left subtree', 'Return null'],
        correct: 2,
        explanationShort: 'If both nodes are in the left subtree, their LCA must also be in the left subtree. Recurse left. Use BST property to avoid full traversal.',
        tags: ['bst', 'lca'],
      },
    ],
  },

  // ─── UNIT 6: Python Patterns ─────────────────────────────────────────────────

  {
    id: 'codr6py-lesson1', name: 'List & Dict Comprehensions', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6py-lesson1-q1', type: 'multiple_choice',
        question: 'What does `[x**2 for x in range(5)]` produce?',
        options: ['[0, 1, 2, 3, 4]', '[1, 4, 9, 16, 25]', '[0, 1, 4, 9, 16]', '[0, 2, 4, 6, 8]'],
        correct: 2,
        explanationShort: 'range(5) = 0,1,2,3,4. Squaring: 0²=0, 1²=1, 2²=4, 3²=9, 4²=16.',
        tags: ['python', 'comprehension'],
      },
      {
        id: 'codr6py-lesson1-q2', type: 'multiple_choice',
        question: '`{k: v for k, v in d.items() if v > 0}` does what?',
        options: [
          'Creates a dict with all items from d',
          'Creates a new dict with only items where value is positive',
          'Removes items with value ≤ 0 from d in place',
          'Sorts d by value',
        ],
        correct: 1,
        explanationShort: 'Dict comprehension with an `if` clause filters items. A new dict is created — d itself is unchanged.',
        tags: ['python', 'dict_comprehension'],
      },
      {
        id: 'codr6py-lesson1-q3', type: 'multiple_choice',
        question: 'Most Pythonic way to filter a list for positive values:',
        options: [
          'result = []; for x in lst: if x > 0: result.append(x)',
          'result = list(filter(lambda x: x > 0, lst))',
          'result = [x for x in lst if x > 0]',
          'result = {x for x in lst if x > 0}',
        ],
        correct: 2,
        explanationShort: 'List comprehensions are idiomatic Python. The filter/lambda form works but is less readable. Option D returns a set (no order, no duplicates).',
        tags: ['python', 'comprehension', 'style'],
      },
      {
        id: 'codr6py-lesson1-q4', type: 'multiple_choice',
        question: '`{x % 3 for x in range(10)}` produces:',
        options: ['{0,1,2,3,4,5,6,7,8,9}', '{0, 1, 2}', '{3, 6, 9}', '{0, 3, 6, 9}'],
        correct: 1,
        explanationShort: 'x%3 for x in 0..9 gives 0,1,2,0,1,2,0,1,2,0. As a set: {0,1,2}.',
        tags: ['python', 'set_comprehension'],
      },
    ],
  },

  {
    id: 'codr6py-lesson2', name: 'collections.Counter & defaultdict', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6py-lesson2-q1', type: 'multiple_choice',
        question: '`Counter("aabbc")` produces:',
        options: ["{'a':1,'b':1,'c':1}", "{'a':2,'b':2,'c':1}", "['a','a','b','b','c']", "{0:'a',1:'b',2:'c'}"],
        correct: 1,
        explanationShort: 'Counter counts element frequencies. \'a\' appears twice, \'b\' twice, \'c\' once.',
        tags: ['python', 'counter'],
      },
      {
        id: 'codr6py-lesson2-q2', type: 'multiple_choice',
        question: '`Counter.most_common(2)` returns:',
        options: [
          'The two elements with the smallest counts',
          'The two elements with the largest counts as (element, count) pairs',
          'The counts sorted alphabetically',
          'A dict of the top 2',
        ],
        correct: 1,
        explanationShort: 'most_common(k) returns the k elements with highest frequency as [(elem, count), ...], sorted descending.',
        tags: ['python', 'counter'],
      },
      {
        id: 'codr6py-lesson2-q3', type: 'multiple_choice',
        question: '`defaultdict(list)` — accessing a missing key does what?',
        options: ['Raises a KeyError', 'Returns None', 'Creates an empty list for that key', 'Removes the key from the dict'],
        correct: 2,
        explanationShort: 'defaultdict calls its factory function on missing keys. defaultdict(list) auto-creates [] — no need for "if key not in d: d[key] = []".',
        tags: ['python', 'defaultdict'],
      },
      {
        id: 'codr6py-lesson2-q4', type: 'multiple_choice',
        question: 'Building a graph adjacency list — most concise approach:',
        options: [
          'Manually check `if node not in graph: graph[node] = []` before each append',
          '`graph = defaultdict(list); graph[u].append(v)`',
          '`graph = Counter()`',
          '`graph = set()`',
        ],
        correct: 1,
        explanationShort: 'defaultdict(list) eliminates the existence check. graph[u].append(v) just works — if u is new, an empty list is created automatically.',
        tags: ['python', 'defaultdict', 'graphs'],
      },
    ],
  },

  {
    id: 'codr6py-lesson3', name: 'heapq & Priority Queue', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6py-lesson3-q1', type: 'multiple_choice',
        question: 'Python\'s `heapq` module implements a:',
        options: ['Max-heap — largest at top', 'Min-heap — smallest at top', 'Sorted list', 'Binary search tree'],
        correct: 1,
        explanationShort: 'heapq is always a min-heap. heappop() always returns the smallest element.',
        tags: ['python', 'heapq'],
      },
      {
        id: 'codr6py-lesson3-q2', type: 'multiple_choice',
        question: 'To use Python\'s heapq as a MAX-heap:',
        options: [
          'Import maxheapq instead',
          'Reverse the list after heapify',
          'Negate values on push, negate again on pop',
          'Use sorted() in reverse',
        ],
        correct: 2,
        explanationShort: 'Push -x, pop gives -min(-x) = max. A common trick since Python has no built-in max-heap.',
        tags: ['python', 'heapq', 'max_heap'],
      },
      {
        id: 'codr6py-lesson3-q3', type: 'multiple_choice',
        question: '`heapq.nlargest(k, nums)` time complexity:',
        options: ['O(n log n)', 'O(n log k)', 'O(k)', 'O(n)'],
        correct: 1,
        explanationShort: 'Maintain a min-heap of size k. For each of n elements: compare and maybe push/pop in O(log k). Total: O(n log k).',
        tags: ['python', 'heapq', 'complexity'],
      },
      {
        id: 'codr6py-lesson3-q4', type: 'multiple_choice',
        question: 'Which problem is a natural fit for a heap?',
        options: [
          'Reversing a list',
          'Detecting a cycle in a linked list',
          'Finding the k-th smallest element from a stream',
          'Checking if a string is a palindrome',
        ],
        correct: 2,
        explanationShort: 'A max-heap of size k holds the k smallest elements seen so far. The heap top is the k-th smallest. O(n log k) overall.',
        tags: ['python', 'heapq', 'use_cases'],
      },
    ],
  },

  {
    id: 'codr6py-lesson4', name: 'itertools Tricks', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6py-lesson4-q1', type: 'multiple_choice',
        question: '`list(itertools.combinations([1,2,3], 2))` produces:',
        options: ['[(1,2),(1,3),(2,3)]', '[(1,2),(2,1),(1,3),(3,1),(2,3),(3,2)]', '[(1,1),(2,2),(3,3)]', '[1,2,3]'],
        correct: 0,
        explanationShort: 'combinations picks r elements in order, no repetition, order doesn\'t matter. 3 choose 2 = 3 pairs.',
        tags: ['python', 'itertools'],
      },
      {
        id: 'codr6py-lesson4-q2', type: 'multiple_choice',
        question: 'Difference between `combinations` and `permutations`:',
        options: [
          'No difference',
          'combinations allows repeats; permutations does not',
          'combinations treats order as irrelevant (AB == BA); permutations treats order as distinct',
          'permutations only works on numbers',
        ],
        correct: 2,
        explanationShort: 'combinations([1,2], 2) → [(1,2)]. permutations([1,2], 2) → [(1,2),(2,1)]. Same elements, different orders.',
        tags: ['python', 'itertools'],
      },
      {
        id: 'codr6py-lesson4-q3', type: 'multiple_choice',
        question: '`list(itertools.accumulate([1,2,3,4]))` produces:',
        options: ['[1,2,3,4]', '[1,3,6,10]', '[24,12,4,1]', '[0,1,3,6]'],
        correct: 1,
        explanationShort: 'accumulate computes running totals: 1, 1+2=3, 3+3=6, 6+4=10. It\'s prefix sums in one line.',
        tags: ['python', 'itertools', 'prefix_sum'],
      },
      {
        id: 'codr6py-lesson4-q4', type: 'multiple_choice',
        question: '`list(itertools.chain([1,2], [3,4]))` produces:',
        options: ['[[1,2],[3,4]]', '[(1,3),(2,4)]', '[1,2,3,4]', '[1,2]'],
        correct: 2,
        explanationShort: 'chain flattens multiple iterables into a single sequence. No nesting — just concatenation.',
        tags: ['python', 'itertools'],
      },
    ],
  },

  {
    id: 'codr6py-quiz', name: 'Unit 6 Quiz', unit: 6, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr6py-quiz-q1', type: 'multiple_choice',
        question: 'Counter("hello") - Counter("world") produces:',
        options: [
          "Counter({'h':1,'e':1,'l':1})",
          "Counter({'h':1,'e':1,'l':2,'o':1})",
          'An error — Counter subtraction is not supported',
          "Counter({'w':1,'o':1,'r':1,'l':1,'d':1})",
        ],
        correct: 0,
        explanationShort: 'hello:{h:1,e:1,l:2,o:1} minus world:{w:1,o:1,r:1,l:1,d:1}. Subtract matching counts, drop zeros/negatives: {h:1,e:1,l:1}.',
        tags: ['python', 'counter'],
      },
      {
        id: 'codr6py-quiz-q2', type: 'multiple_choice',
        question: 'Most efficient way to get the 3 most frequent words from a list:',
        options: [
          'Sort the list then count manually',
          'Counter(words).most_common(3)',
          'sorted(Counter(words).items(), key=lambda x: -x[1])[:3]',
          'heapq.nlargest(3, words)',
        ],
        correct: 1,
        explanationShort: 'most_common(k) is O(n log k) internally. Option C works but is more verbose. Option D would sort by word, not frequency.',
        tags: ['python', 'counter'],
      },
      {
        id: 'codr6py-quiz-q3', type: 'multiple_choice',
        question: '`list(itertools.combinations_with_replacement([1,2], 2))`:',
        options: ['[(1,1),(1,2),(2,2)]', '[(1,2),(2,1)]', '[(1,1),(1,2),(2,1),(2,2)]', '[(1,2)]'],
        correct: 0,
        explanationShort: 'combinations_with_replacement allows repeating elements. Order still doesn\'t matter: (1,1), (1,2), (2,2).',
        tags: ['python', 'itertools'],
      },
      {
        id: 'codr6py-quiz-q4', type: 'multiple_choice',
        question: 'Counting word frequencies — `defaultdict(int)` vs `defaultdict(list)`:',
        options: [
          'defaultdict(list) — store all occurrences in a list, then count len()',
          'defaultdict(int) — default is 0, just increment: freq[word] += 1',
          'Neither — use a regular dict with .get()',
          'defaultdict(set) — store unique counts',
        ],
        correct: 1,
        explanationShort: 'defaultdict(int) starts each new key at 0. freq[word] += 1 is clean and fast. defaultdict(list) would work but is indirect.',
        tags: ['python', 'defaultdict'],
      },
      {
        id: 'codr6py-quiz-q5', type: 'multiple_choice',
        question: 'heapq.heappush() and heapq.heappop() both run in:',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
        correct: 1,
        explanationShort: 'Push sifts up, pop sifts down — both traverse the heap height = O(log n). heapify() on an existing list is O(n).',
        tags: ['python', 'heapq', 'complexity'],
      },
    ],
  },

  // ─── UNIT 7: Pythonic Problem Solving ────────────────────────────────────────

  {
    id: 'codr7py-lesson1', name: 'String Manipulation in Python', unit: 7, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr7py-lesson1-q1', type: 'multiple_choice',
        question: '`"hello"[::-1]` produces:',
        options: ['"hello"', '"olleh"', "['h','e','l','l','o']", '"heoll"'],
        correct: 1,
        explanationShort: 'Slice [start:stop:step] with step=-1 reverses the string. This is the idiomatic Python one-liner.',
        tags: ['python', 'strings'],
      },
      {
        id: 'codr7py-lesson1-q2', type: 'multiple_choice',
        question: '`"abc".join(["x","y","z"])` produces:',
        options: ['"xyzabc"', '"abcxyzabc"', '"xabcyabcz"', '"abc"'],
        correct: 2,
        explanationShort: 'join inserts the separator BETWEEN elements. "abc".join(["x","y","z"]) = "x" + "abc" + "y" + "abc" + "z" = "xabcyabcz".',
        tags: ['python', 'strings'],
      },
      {
        id: 'codr7py-lesson1-q3', type: 'multiple_choice',
        question: 'Fastest way to build a string from a list of parts in Python:',
        options: [
          'Repeated += concatenation — creates a new string each time: O(n²)',
          '"".join(parts) — one allocation: O(n)',
          'str(parts) — converts the list directly',
          'Using a StringIO buffer',
        ],
        correct: 1,
        explanationShort: 'str += creates a new string object every time — O(n²) total. "".join() allocates once with the final size — O(n).',
        tags: ['python', 'strings', 'performance'],
      },
      {
        id: 'codr7py-lesson1-q4', type: 'multiple_choice',
        question: '`s.split()` vs `s.split(" ")` — key difference:',
        options: [
          'No difference',
          's.split() splits on any whitespace and strips leading/trailing; s.split(" ") splits on single space only and keeps empty strings',
          's.split(" ") is faster',
          's.split() raises an error on empty strings',
        ],
        correct: 1,
        explanationShort: '"  a  b".split() → [\'a\',\'b\']. "  a  b".split(" ") → [\'\',\'\',\'a\',\'\',\'b\']. The no-arg form is usually what you want.',
        tags: ['python', 'strings'],
      },
    ],
  },

  {
    id: 'codr7py-lesson2', name: 'Lambda & Functional Patterns', unit: 7, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr7py-lesson2-q1', type: 'multiple_choice',
        question: '`sorted(words, key=lambda w: len(w))` sorts words by:',
        options: ['Alphabetical order', 'Reverse alphabetical', 'Length (shortest first)', 'Length (longest first)'],
        correct: 2,
        explanationShort: 'The key function extracts the sort criterion. len(w) means sort by character count, ascending by default.',
        tags: ['python', 'lambda', 'sorting'],
      },
      {
        id: 'codr7py-lesson2-q2', type: 'multiple_choice',
        question: '`list(map(lambda x: x*2, [1,2,3]))` returns:',
        options: ['[1,2,3]', '[2,4,6]', '[1,4,9]', '12'],
        correct: 1,
        explanationShort: 'map applies the function to each element lazily. list() forces evaluation: [1*2, 2*2, 3*2] = [2,4,6].',
        tags: ['python', 'lambda', 'map'],
      },
      {
        id: 'codr7py-lesson2-q3', type: 'multiple_choice',
        question: '`list(filter(None, [0, 1, "", "hello", False, True]))` returns:',
        options: ['[0,1,"","hello",False,True]', '[1,"hello",True]', '[0,"",False]', '[1,2,3]'],
        correct: 1,
        explanationShort: 'filter(None, ...) keeps elements that are truthy. 0, "", and False are falsy — they\'re filtered out.',
        tags: ['python', 'lambda', 'filter'],
      },
      {
        id: 'codr7py-lesson2-q4', type: 'multiple_choice',
        question: 'Which is generally more Pythonic — map/filter or list comprehensions?',
        options: [
          'map/filter — they are always faster',
          'List comprehensions — clearer intent, preferred by the Python community',
          'map/filter — they compose better',
          'Both are equally idiomatic',
        ],
        correct: 1,
        explanationShort: 'PEP 8 and the Python community generally prefer comprehensions for readability. map/filter can be useful for partial application.',
        tags: ['python', 'style'],
      },
    ],
  },

  {
    id: 'codr7py-lesson3', name: 'Time & Space Complexity in Python', unit: 7, market: 'shared', xpReward: 30,
    questions: [
      {
        id: 'codr7py-lesson3-q1', type: 'multiple_choice',
        question: '`list.append(x)` time complexity:',
        options: ['O(n) — shifts all elements', 'O(log n)', 'O(1) amortized', 'O(n²)'],
        correct: 2,
        explanationShort: 'append is O(1) amortized. When the list doubles in size, it copies all elements — but this happens rarely enough that average cost stays O(1).',
        tags: ['python', 'complexity', 'list'],
      },
      {
        id: 'codr7py-lesson3-q2', type: 'multiple_choice',
        question: '`x in some_list` vs `x in some_set` — time complexity of each?',
        options: ['Both O(1)', 'Both O(n)', 'list: O(n), set: O(1) average', 'list: O(log n), set: O(1)'],
        correct: 2,
        explanationShort: 'List membership scans elements linearly. Set uses a hash table — O(1) average. Use a set when you do many membership checks.',
        tags: ['python', 'complexity', 'set'],
      },
      {
        id: 'codr7py-lesson3-q3', type: 'multiple_choice',
        question: 'Recursive Fibonacci without memoization — time complexity:',
        options: ['O(n)', 'O(n log n)', 'O(2^n)', 'O(n²)'],
        correct: 2,
        explanationShort: 'fib(n) = fib(n-1) + fib(n-2) spawns a binary tree of calls. The tree has ~2^n leaves — exponential.',
        tags: ['python', 'complexity', 'recursion'],
      },
      {
        id: 'codr7py-lesson3-q4', type: 'multiple_choice',
        question: 'Adding `@lru_cache` to recursive Fibonacci reduces complexity to:',
        options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(1)'],
        correct: 1,
        explanationShort: 'With memoization, each unique fib(k) is computed once. There are n unique subproblems — O(n) time, O(n) space.',
        tags: ['python', 'complexity', 'memoization'],
      },
      {
        id: 'codr7py-lesson3-q5', type: 'multiple_choice',
        question: 'Python list slicing `lst[a:b]` — time complexity:',
        options: ['O(1) — returns a view', 'O(b - a) — copies the slice', 'O(n) — always copies the whole list', 'O(log n)'],
        correct: 1,
        explanationShort: 'Slicing creates a NEW list containing b-a elements. It\'s O(k) where k is the slice length. Unlike NumPy, Python slices are copies.',
        tags: ['python', 'complexity', 'list'],
      },
    ],
  },

  {
    id: 'codr7py-quiz', name: 'Unit 7 Quiz', unit: 7, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr7py-quiz-q1', type: 'multiple_choice',
        question: 'Most Pythonic way to reverse a string:',
        options: ['list(reversed(s))', 's[::-1]', 's.reverse()', 'Writing a loop with two pointers'],
        correct: 1,
        explanationShort: 's[::-1] is the idiomatic one-liner. reversed(s) returns an iterator — you\'d need "".join(reversed(s)). s.reverse() only works on lists.',
        tags: ['python', 'strings', 'style'],
      },
      {
        id: 'codr7py-quiz-q2', type: 'multiple_choice',
        question: '`dict.get(key)` time complexity in Python:',
        options: ['O(n)', 'O(log n)', 'O(1) average', 'O(n²)'],
        correct: 2,
        explanationShort: 'dict is a hash map — O(1) average lookup. .get() is equivalent to [] but returns None (or a default) instead of raising KeyError.',
        tags: ['python', 'complexity', 'dict'],
      },
      {
        id: 'codr7py-quiz-q3', type: 'multiple_choice',
        question: '`sum([[1,2],[3,4],[5,6]], [])` flattens a list. Its complexity is:',
        options: ['O(n)', 'O(n²) — quadratic due to repeated list concatenation', 'O(log n)', 'O(1)'],
        correct: 1,
        explanationShort: 'Each + creates a new list, copying all previous elements. Like string += in a loop — use itertools.chain.from_iterable() for O(n).',
        tags: ['python', 'complexity', 'performance'],
      },
      {
        id: 'codr7py-quiz-q4', type: 'multiple_choice',
        question: 'When should you use a generator expression instead of a list comprehension?',
        options: [
          'Never — list comprehensions are always faster',
          'When you need random access to elements by index',
          'When processing a large sequence one element at a time — generators are lazy and save memory',
          'When the sequence contains strings',
        ],
        correct: 2,
        explanationShort: 'sum(x**2 for x in range(10**9)) never builds the full list in memory. A list comprehension would need 8GB+ RAM.',
        tags: ['python', 'generators', 'memory'],
      },
      {
        id: 'codr7py-quiz-q5', type: 'multiple_choice',
        question: 'Python\'s `sorted()` uses Timsort. Its time complexity:',
        options: ['O(n) best case, O(n log n) worst', 'Always O(n log n)', 'Always O(n²)', 'O(log n)'],
        correct: 0,
        explanationShort: 'Timsort exploits existing runs — nearly sorted input is O(n). Worst case (random data) is O(n log n). Always stable.',
        tags: ['python', 'complexity', 'sorting'],
      },
    ],
  },

  // ─── UNIT 6 Java: Java Patterns ──────────────────────────────────────────────

  {
    id: 'codr6ja-lesson1', name: 'HashMap & HashSet', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6ja-lesson1-q1', type: 'multiple_choice',
        question: 'How do you safely get a value from a Java HashMap with a fallback if the key is missing?',
        options: [
          'map.get(key) — returns null if missing',
          'map.getOrDefault(key, defaultValue)',
          'map.contains(key) ? map.get(key) : defaultValue — verbose but works',
          'map.fetch(key, defaultValue)',
        ],
        correct: 1,
        explanationShort: 'getOrDefault() is the clean Java idiom. map.get() returns null for missing keys — a common source of NullPointerExceptions.',
        tags: ['java', 'hashmap'],
      },
      {
        id: 'codr6ja-lesson1-q2', type: 'multiple_choice',
        question: 'Key difference between HashSet and TreeSet in Java:',
        options: [
          'No difference — both store unique elements',
          'HashSet: O(1) add/contains; TreeSet: O(log n) but keeps elements sorted',
          'TreeSet is faster for all operations',
          'HashSet allows duplicates; TreeSet does not',
        ],
        correct: 1,
        explanationShort: 'HashSet is backed by a hash table — O(1). TreeSet is backed by a Red-Black tree — O(log n) but sorted iteration.',
        tags: ['java', 'hashset', 'treeset'],
      },
      {
        id: 'codr6ja-lesson1-q3', type: 'multiple_choice',
        question: 'To count character frequencies in Java, which approach is most idiomatic?',
        options: [
          'Sort the string and count consecutive chars',
          'map.merge(c, 1, Integer::sum) for each char in s.toCharArray()',
          'Use a 26-element int[] for lowercase letters',
          'Collections.frequency(list, char)',
        ],
        correct: 1,
        explanationShort: 'merge(key, value, remappingFn) is the clean Java idiom: inserts 1 if absent, otherwise applies the function (Integer::sum adds 1 to existing).',
        tags: ['java', 'hashmap', 'frequency'],
      },
      {
        id: 'codr6ja-lesson1-q4', type: 'multiple_choice',
        question: '`HashMap.getOrDefault(key, 0)` — if key exists with value 5, what does it return?',
        options: ['0 — always returns the default', '5', 'null', 'An exception'],
        correct: 1,
        explanationShort: 'getOrDefault returns the value if the key exists. The default (0) is only returned when the key is absent.',
        tags: ['java', 'hashmap'],
      },
    ],
  },

  {
    id: 'codr6ja-lesson2', name: 'PriorityQueue & TreeMap', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6ja-lesson2-q1', type: 'multiple_choice',
        question: 'Java\'s `PriorityQueue` is by default a:',
        options: ['Max-heap', 'Min-heap', 'FIFO queue', 'Sorted list'],
        correct: 1,
        explanationShort: 'Java\'s PriorityQueue uses natural ordering by default — smaller elements have higher priority (min-heap).',
        tags: ['java', 'priorityqueue'],
      },
      {
        id: 'codr6ja-lesson2-q2', type: 'multiple_choice',
        question: 'To create a MAX-heap in Java using PriorityQueue:',
        options: [
          'new PriorityQueue<>(Collections.reverseOrder())',
          'new MaxPriorityQueue<>()',
          'new PriorityQueue<>(Comparator.naturalOrder().reversed())',
          'Java doesn\'t support max-heaps',
        ],
        correct: 0,
        explanationShort: 'Pass a reversed comparator. Collections.reverseOrder() is shorthand for (a,b) -> b.compareTo(a).',
        tags: ['java', 'priorityqueue', 'max_heap'],
      },
      {
        id: 'codr6ja-lesson2-q3', type: 'multiple_choice',
        question: 'What does TreeMap guarantee that HashMap does not?',
        options: ['O(1) lookup', 'Keys are iterated in sorted order', 'Values are unique', 'Thread safety'],
        correct: 1,
        explanationShort: 'TreeMap (Red-Black tree) keeps keys sorted. HashMap offers O(1) ops but random iteration order.',
        tags: ['java', 'treemap'],
      },
      {
        id: 'codr6ja-lesson2-q4', type: 'multiple_choice',
        question: '`PriorityQueue.peek()` vs `PriorityQueue.poll()`:',
        options: [
          'No difference',
          'peek() returns and removes; poll() only returns',
          'peek() returns without removing; poll() returns and removes',
          'peek() throws if empty; poll() returns null',
        ],
        correct: 2,
        explanationShort: 'peek() = view the top without changing the heap. poll() = remove and return the top. Both return null if the queue is empty.',
        tags: ['java', 'priorityqueue'],
      },
    ],
  },

  {
    id: 'codr6ja-lesson3', name: 'Interfaces & Generics', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6ja-lesson3-q1', type: 'multiple_choice',
        question: 'In Java, `List<T>` means:',
        options: [
          'A list that stores only one object named T',
          'A generic list parameterised by type T — type-safe at compile time',
          'A list that can hold any object (same as raw List)',
          'A template that generates a list class at runtime',
        ],
        correct: 1,
        explanationShort: 'Generics enforce type safety at compile time. List<String> accepts only Strings — no casting, no ClassCastException at runtime.',
        tags: ['java', 'generics'],
      },
      {
        id: 'codr6ja-lesson3-q2', type: 'multiple_choice',
        question: '`Comparable<T>` vs `Comparator<T>` — key difference:',
        options: [
          'No difference',
          'Comparable defines natural ordering inside the class; Comparator defines external custom orderings',
          'Comparator is in java.lang; Comparable requires an import',
          'Comparable compares two different objects; Comparator compares an object to itself',
        ],
        correct: 1,
        explanationShort: 'Comparable: "I know how to compare myself to another T" (compareTo). Comparator: "I compare two T objects from outside" (compare).',
        tags: ['java', 'comparable', 'comparator'],
      },
      {
        id: 'codr6ja-lesson3-q3', type: 'multiple_choice',
        question: '`Collections.sort(list)` requires list elements to implement:',
        options: ['Comparator', 'Comparable', 'Serializable', 'Iterable'],
        correct: 1,
        explanationShort: 'sort(list) uses the natural ordering — elements must implement Comparable (i.e. have compareTo). Pass a Comparator for custom ordering.',
        tags: ['java', 'comparable', 'sorting'],
      },
      {
        id: 'codr6ja-lesson3-q4', type: 'multiple_choice',
        question: 'What does `? extends Number` mean in a Java generic method signature?',
        options: [
          'Exactly the Number class, no subclasses',
          'Any type that is a subclass of Number (upper bounded wildcard)',
          'Any type that Number is a subclass of',
          'A wildcard that prevents any type from being passed',
        ],
        correct: 1,
        explanationShort: 'Upper bounded wildcard — accepts Number or any of its subclasses (Integer, Double, etc.). Useful for read-only collections.',
        tags: ['java', 'generics', 'wildcards'],
      },
    ],
  },

  {
    id: 'codr6ja-lesson4', name: 'ArrayDeque vs LinkedList', unit: 6, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr6ja-lesson4-q1', type: 'multiple_choice',
        question: 'Which is preferred as a stack/queue in Java — ArrayDeque or LinkedList?',
        options: [
          'LinkedList — more versatile',
          'ArrayDeque — faster in practice (cache-friendly, no per-node allocation)',
          'Stack — the built-in stack class',
          'ArrayList — supports random access',
        ],
        correct: 1,
        explanationShort: 'ArrayDeque is recommended by Java docs since Java 6. It avoids LinkedList\'s node allocation overhead and is more cache-friendly.',
        tags: ['java', 'deque', 'arraydeque'],
      },
      {
        id: 'codr6ja-lesson4-q2', type: 'multiple_choice',
        question: 'Push to and pop from a STACK using ArrayDeque in Java:',
        options: ['push() and pop()', 'add() and remove()', 'offer() and poll()', 'enqueue() and dequeue()'],
        correct: 0,
        explanationShort: 'ArrayDeque implements the Deque interface with stack methods: push() adds to front (top), pop() removes from front.',
        tags: ['java', 'deque', 'stack'],
      },
      {
        id: 'codr6ja-lesson4-q3', type: 'multiple_choice',
        question: 'For a QUEUE (FIFO) using ArrayDeque, which method pair is correct?',
        options: ['push() and pop()', 'offerFirst() and pollLast()', 'offer() and poll()', 'add() and peek()'],
        correct: 2,
        explanationShort: 'offer() adds to the tail, poll() removes from the head. This is FIFO — first added, first out.',
        tags: ['java', 'deque', 'queue'],
      },
      {
        id: 'codr6ja-lesson4-q4', type: 'multiple_choice',
        question: 'ArrayDeque vs LinkedList for BFS in Java — which to prefer and why?',
        options: [
          'LinkedList — supports null elements',
          'ArrayDeque — contiguous memory, no per-element node allocation, better cache performance',
          'LinkedList — O(1) access at any index',
          'No difference — both are O(1) for queue ops',
        ],
        correct: 1,
        explanationShort: 'Both are O(1) for queue ops, but ArrayDeque\'s array-based storage is cache-friendly. LinkedList allocates a new Node object per element.',
        tags: ['java', 'deque', 'performance'],
      },
    ],
  },

  {
    id: 'codr6ja-quiz', name: 'Unit 6 Quiz', unit: 6, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr6ja-quiz-q1', type: 'multiple_choice',
        question: 'Top-k frequent elements in Java — most efficient approach:',
        options: [
          'Sort the frequency map by value — O(n log n)',
          'Min-heap of size k, iterate the frequency map — O(n log k)',
          'Max-heap of all elements — O(n log n)',
          'Sort the original array — O(n log n)',
        ],
        correct: 1,
        explanationShort: 'Build a min-heap of size k. For each element in the frequency map, push if heap has room or if freq > heap min. O(n log k).',
        tags: ['java', 'priorityqueue', 'frequency'],
      },
      {
        id: 'codr6ja-quiz-q2', type: 'multiple_choice',
        question: 'You need to iterate a Map in Java in KEY-SORTED order. Which collection?',
        options: ['HashMap', 'LinkedHashMap', 'TreeMap', 'PriorityQueue<Map.Entry<K,V>>'],
        correct: 2,
        explanationShort: 'TreeMap maintains keys in sorted order. HashMap is unordered. LinkedHashMap preserves insertion order.',
        tags: ['java', 'treemap'],
      },
      {
        id: 'codr6ja-quiz-q3', type: 'multiple_choice',
        question: 'Risk of writing Comparator as `(a, b) -> a - b` for integers:',
        options: [
          'It doesn\'t compile',
          'Integer overflow if a and b have large values of opposite signs',
          'It sorts in descending order',
          'It only works for positive integers',
        ],
        correct: 1,
        explanationShort: 'If a = Integer.MAX_VALUE and b = -1, a - b overflows. Prefer Integer.compare(a, b) which handles all cases safely.',
        tags: ['java', 'comparator', 'overflow'],
      },
      {
        id: 'codr6ja-quiz-q4', type: 'multiple_choice',
        question: 'Which Java collection guarantees insertion-order iteration AND is backed by a hash table?',
        options: ['HashMap', 'TreeMap', 'LinkedHashMap', 'ArrayDeque'],
        correct: 2,
        explanationShort: 'LinkedHashMap = HashMap + doubly-linked list tracking insertion order. O(1) ops, predictable iteration order.',
        tags: ['java', 'linkedhashmap'],
      },
      {
        id: 'codr6ja-quiz-q5', type: 'multiple_choice',
        question: '`Comparator.thenComparing()` is used when:',
        options: [
          'The primary comparator always resolves ties',
          'You want to sort by a secondary key when the primary comparison returns 0',
          'You want to combine two criteria with OR logic',
          'The comparator needs to sort in reverse',
        ],
        correct: 1,
        explanationShort: 'thenComparing chains comparators. Primary runs first; if it returns 0 (tie), secondary runs. Like SQL ORDER BY a, b.',
        tags: ['java', 'comparator'],
      },
    ],
  },

  // ─── UNIT 7 Java: Java Problem Solving ───────────────────────────────────────

  {
    id: 'codr7ja-lesson1', name: 'String Manipulation in Java', unit: 7, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr7ja-lesson1-q1', type: 'multiple_choice',
        question: 'Why use StringBuilder over String concatenation in a loop?',
        options: [
          'StringBuilder is thread-safe',
          'String is immutable; each += creates a new object — O(n²) total; StringBuilder is O(n)',
          'StringBuilder supports regex',
          'The compiler always optimises += anyway',
        ],
        correct: 1,
        explanationShort: 'Java Strings are immutable. "a" + "b" creates a third string. In a loop of n iterations: O(1+2+…+n) = O(n²). StringBuilder mutates in place.',
        tags: ['java', 'strings', 'stringbuilder'],
      },
      {
        id: 'codr7ja-lesson1-q2', type: 'multiple_choice',
        question: '`String.charAt(i)` returns a:',
        options: ['String of length 1', 'int (ASCII code)', 'char', 'byte'],
        correct: 2,
        explanationShort: 'charAt returns a char (16-bit Unicode). Cast to int to get the ASCII/Unicode value: (int) s.charAt(i).',
        tags: ['java', 'strings'],
      },
      {
        id: 'codr7ja-lesson1-q3', type: 'multiple_choice',
        question: 'Most concise way to reverse a string in Java:',
        options: [
          'Write a loop with two pointers on a char array',
          'new StringBuilder(s).reverse().toString()',
          'String.reverse(s)',
          'Arrays.sort(s.toCharArray())',
        ],
        correct: 1,
        explanationShort: 'StringBuilder has a built-in reverse() method. This is the idiomatic Java one-liner for string reversal.',
        tags: ['java', 'strings', 'stringbuilder'],
      },
      {
        id: 'codr7ja-lesson1-q4', type: 'multiple_choice',
        question: '`s.split("\\\\s+")` vs `s.split(" ")` — difference:',
        options: [
          'No difference',
          '"\\\\s+" splits on any whitespace (tabs, newlines, multiple spaces); " " splits on exactly one space character',
          '"\\\\s+" is slower',
          '" " handles all whitespace types',
        ],
        correct: 1,
        explanationShort: '\\s+ is a regex matching one or more whitespace chars. " " is a literal single space — multiple spaces produce empty strings.',
        tags: ['java', 'strings', 'regex'],
      },
    ],
  },

  {
    id: 'codr7ja-lesson2', name: 'Comparable & Comparator', unit: 7, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr7ja-lesson2-q1', type: 'multiple_choice',
        question: '`compareTo` should return what convention?',
        options: [
          'true or false',
          'Negative if this < other, 0 if equal, positive if this > other',
          'The difference as a String',
          'A value from 0 to 100',
        ],
        correct: 1,
        explanationShort: 'Standard contract: negative = less than, 0 = equal, positive = greater than. The magnitude doesn\'t matter — only the sign.',
        tags: ['java', 'comparable'],
      },
      {
        id: 'codr7ja-lesson2-q2', type: 'multiple_choice',
        question: 'To sort `List<int[]>` by the second element of each array:',
        options: [
          'Collections.sort(list) — uses natural ordering',
          'list.sort(Comparator.comparingInt(a -> a[1]))',
          'Arrays.sort(list) — sorts by first element',
          'Implement Comparable on int[]',
        ],
        correct: 1,
        explanationShort: 'int[] doesn\'t implement Comparable. Pass a Comparator lambda that extracts the comparison key.',
        tags: ['java', 'comparator', 'sorting'],
      },
      {
        id: 'codr7ja-lesson2-q3', type: 'multiple_choice',
        question: 'Safe integer comparator (avoids overflow):',
        options: [
          '(a, b) -> a - b',
          '(a, b) -> Integer.compare(a, b)',
          '(a, b) -> a > b ? 1 : 0',
          '(a, b) -> Math.abs(a - b)',
        ],
        correct: 1,
        explanationShort: 'Integer.compare handles all edge cases including overflow. a - b overflows when a and b are large values of opposite signs.',
        tags: ['java', 'comparator', 'overflow'],
      },
      {
        id: 'codr7ja-lesson2-q4', type: 'multiple_choice',
        question: '`Comparator.thenComparing()` — when does the secondary comparator run?',
        options: [
          'Always, ignoring the primary result',
          'Only when the primary comparator returns 0 (a tie)',
          'Only when the primary comparator returns a positive value',
          'Never — it\'s for documentation only',
        ],
        correct: 1,
        explanationShort: 'thenComparing breaks ties. If primary returns 0, secondary runs. Otherwise, primary\'s result is used as-is.',
        tags: ['java', 'comparator'],
      },
    ],
  },

  {
    id: 'codr7ja-lesson3', name: 'Time & Space Complexity in Java', unit: 7, market: 'shared', xpReward: 30,
    questions: [
      {
        id: 'codr7ja-lesson3-q1', type: 'multiple_choice',
        question: '`ArrayList.get(i)` time complexity:',
        options: ['O(n)', 'O(log n)', 'O(1)', 'O(i)'],
        correct: 2,
        explanationShort: 'ArrayList is backed by an array — index access is O(1). This is ArrayList\'s key advantage over LinkedList.',
        tags: ['java', 'complexity', 'arraylist'],
      },
      {
        id: 'codr7ja-lesson3-q2', type: 'multiple_choice',
        question: '`LinkedList.get(i)` time complexity:',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
        correct: 2,
        explanationShort: 'LinkedList must traverse from head (or tail) to index i — O(n). Use it as a queue/deque, not for random access.',
        tags: ['java', 'complexity', 'linkedlist'],
      },
      {
        id: 'codr7ja-lesson3-q3', type: 'multiple_choice',
        question: '`Arrays.sort(int[])` in Java uses:',
        options: [
          'Merge sort — stable, O(n log n)',
          'Dual-pivot quicksort — O(n log n) average',
          'Heapsort — O(n log n) guaranteed',
          'Insertion sort — O(n²)',
        ],
        correct: 1,
        explanationShort: 'Java uses dual-pivot quicksort for primitive arrays (int[], double[], etc.). It\'s fast in practice but not stable.',
        tags: ['java', 'sorting', 'complexity'],
      },
      {
        id: 'codr7ja-lesson3-q4', type: 'multiple_choice',
        question: '`Collections.sort(List<T>)` in Java uses:',
        options: ['Dual-pivot quicksort', 'Timsort — stable O(n log n)', 'Heapsort', 'Insertion sort'],
        correct: 1,
        explanationShort: 'Java uses Timsort for object collections — it\'s stable and exploits existing runs in nearly-sorted data.',
        tags: ['java', 'sorting', 'complexity'],
      },
      {
        id: 'codr7ja-lesson3-q5', type: 'multiple_choice',
        question: 'Auto-boxing `int` to `Integer` in a tight loop — why is this a concern?',
        options: [
          'Not a concern — auto-boxing is free',
          'Each int→Integer creates a new heap object (except cached values -128 to 127)',
          'Auto-boxing causes integer overflow',
          'It changes the value of the int',
        ],
        correct: 1,
        explanationShort: 'Integer.valueOf caches -128 to 127. Outside that range, each boxing creates a new object — GC pressure in tight loops.',
        tags: ['java', 'autoboxing', 'performance'],
      },
    ],
  },

  {
    id: 'codr7ja-quiz', name: 'Unit 7 Quiz', unit: 7, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr7ja-quiz-q1', type: 'multiple_choice',
        question: 'Why is `new Integer(42)` deprecated in modern Java?',
        options: [
          'Nothing — it\'s the standard way',
          'Deprecated; Integer.valueOf(42) uses the integer cache for -128 to 127',
          'It doesn\'t compile in Java 17+',
          'It creates a long instead of int',
        ],
        correct: 1,
        explanationShort: 'Integer.valueOf() reuses cached instances for common values — no heap allocation. new Integer() always allocates. Deprecated since Java 9.',
        tags: ['java', 'integers', 'performance'],
      },
      {
        id: 'codr7ja-quiz-q2', type: 'multiple_choice',
        question: 'StringBuilder.append() is O(1) amortized. What causes the occasional O(n) operation?',
        options: [
          'It never resizes — fixed capacity',
          'When the internal buffer is full, it doubles in size — copying all content',
          'Every 10 appends trigger a resize',
          'The JVM decides when to resize',
        ],
        correct: 1,
        explanationShort: 'Like ArrayList, StringBuilder doubles capacity when full. The copy is O(n) but rare — amortised cost per append is O(1).',
        tags: ['java', 'stringbuilder', 'complexity'],
      },
      {
        id: 'codr7ja-quiz-q3', type: 'multiple_choice',
        question: '`TreeSet` vs `HashSet` for "store unique elements, iterate in sorted order":',
        options: [
          'HashSet — O(n) insertion, then sort separately',
          'TreeSet — O(n log n) insertion, already sorted when you iterate',
          'Identical for this use case',
          'LinkedHashSet — maintains insertion order (not sorted)',
        ],
        correct: 1,
        explanationShort: 'TreeSet = sorted set. HashSet is O(1) per insert but unordered. LinkedHashSet is insertion-ordered but not sorted.',
        tags: ['java', 'treeset', 'hashset'],
      },
      {
        id: 'codr7ja-quiz-q4', type: 'multiple_choice',
        question: 'Fastest Java membership check for a known set of values:',
        options: [
          'List.contains(x) — O(n)',
          'Set.contains(x) — O(1) average',
          'Arrays.binarySearch(sortedArr, x) — O(log n)',
          'Map.containsKey(x) — O(1) average',
        ],
        correct: 1,
        explanationShort: 'Set.contains() is O(1) average — the best option. If you already have a Map, containsKey is equally fast. List is O(n).',
        tags: ['java', 'hashset', 'complexity'],
      },
      {
        id: 'codr7ja-quiz-q5', type: 'multiple_choice',
        question: 'Sort a list of int[] by first element ascending, then by second element descending on ties:',
        options: [
          'list.sort(Comparator.comparingInt(a -> a[0]))',
          'list.sort(Comparator.comparingInt((int[] a) -> a[0]).thenComparing(a -> -a[1]))',
          'list.sort((a,b) -> a[0]-b[0] == 0 ? b[1]-a[1] : a[0]-b[0])',
          'Both B and C work correctly (B is safer due to overflow risk in C)',
        ],
        correct: 3,
        explanationShort: 'Option B uses safe API. Option C uses subtraction (overflow risk for large negatives). In practice B is preferred, but both produce correct output for typical interview inputs.',
        tags: ['java', 'comparator', 'sorting'],
      },
    ],
  },
];

export default CODR_LESSONS_2;
