import type { Lesson } from '../types';

const CODR_LESSONS: Lesson[] = [

  // ─── UNIT 1: Arrays & Hashing ───────────────────────────────────────────────

  {
    id: 'codr1-lesson1', name: 'What is a Hash Map?', unit: 1, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr1-lesson1-q1', type: 'multiple_choice',
        question: 'What is the core purpose of a hash map?',
        options: [
          'Store elements in sorted order',
          'Map keys to values using a hash function for fast lookup',
          'Store unique elements with no duplicates',
          'Maintain insertion order of elements',
        ],
        correct: 1,
        explanationShort: 'A hash map uses a hash function to compute a storage location from the key, giving O(1) average-case lookup.',
        tags: ['hash_map', 'fundamentals'],
      },
      {
        id: 'codr1-lesson1-q2', type: 'multiple_choice',
        question: 'What is the average-case time complexity of looking up a value in a hash map?',
        options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
        correct: 2,
        explanationShort: 'The hash function computes the bucket location directly, so no searching is needed — O(1) on average.',
        tags: ['hash_map', 'complexity'],
      },
      {
        id: 'codr1-lesson1-q3', type: 'multiple_choice',
        question: 'What happens when two different keys produce the same hash value?',
        options: [
          'The second key overwrites the first',
          'The hash map raises an error',
          'A collision occurs and is handled via chaining or open addressing',
          'The first key is deleted automatically',
        ],
        correct: 2,
        explanationShort: 'Collisions are inevitable. Python dicts use open addressing; Java\'s HashMap uses chaining (linked list per bucket).',
        tags: ['hash_map', 'collision'],
      },
      {
        id: 'codr1-lesson1-q4', type: 'multiple_choice',
        question: 'Which Python built-in type is a hash map?',
        options: ['list', 'tuple', 'set', 'dict'],
        correct: 3,
        explanationShort: 'Python\'s dict maps keys to values using a hash table. set is a hash map of keys only (no values).',
        tags: ['hash_map', 'python'],
      },
      {
        id: 'codr1-lesson1-q5', type: 'multiple_choice',
        question: 'Why is O(1) average lookup possible in a hash map?',
        options: [
          'The map keeps all keys sorted',
          'The hash function computes the storage location directly from the key',
          'The map uses binary search on sorted buckets',
          'It searches every element until a match is found',
        ],
        correct: 1,
        explanationShort: 'The hash function maps a key straight to a bucket index — no traversal needed, hence O(1) average.',
        tags: ['hash_map', 'fundamentals'],
      },
    ],
  },

  {
    id: 'codr1-lesson2', name: 'Two Sum Pattern', unit: 1, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr1-lesson2-q1', type: 'multiple_choice',
        question: 'Given nums = [2, 7, 11, 15] and target = 9, which indices produce the target sum?',
        options: ['[0, 1] — 2 + 7 = 9', '[1, 2] — 7 + 11 = 18', '[0, 2] — 2 + 11 = 13', '[2, 3] — 11 + 15 = 26'],
        correct: 0,
        explanationShort: 'nums[0] + nums[1] = 2 + 7 = 9. The hash map approach finds this in a single pass.',
        tags: ['two_sum', 'hash_map'],
      },
      {
        id: 'codr1-lesson2-q2', type: 'multiple_choice',
        question: 'What is the time complexity of the hash map approach to Two Sum?',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'],
        correct: 2,
        explanationShort: 'One pass through the array, O(1) hash map lookup per element — total O(n). Brute force nested loops are O(n²).',
        tags: ['two_sum', 'complexity'],
      },
      {
        id: 'codr1-lesson2-q3', type: 'multiple_choice',
        question: 'In the hash map Two Sum solution, what do we store as the key?',
        codeSnippet: 'def two_sum(nums, target):\n    seen = {}   # {???: index}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[???] = i\n    return []',
        codeLanguage: 'python',
        options: ['The target value', 'The current index', 'The current number', 'The complement'],
        correct: 2,
        explanationShort: 'We store {number: index}. For each new element, we check if its complement (target - num) is already a key.',
        tags: ['two_sum', 'hash_map'],
      },
      {
        id: 'codr1-lesson2-q4', type: 'multiple_choice',
        question: 'Why is the hash map Two Sum better than a brute force nested loop?',
        options: [
          'It uses less memory',
          'It reduces time from O(n²) to O(n) by checking each complement in O(1)',
          'It works on unsorted arrays only',
          'It avoids using extra variables',
        ],
        correct: 1,
        explanationShort: 'The nested loop checks every pair — O(n²). The hash map turns each "does my complement exist?" check into O(1).',
        tags: ['two_sum', 'complexity'],
      },
    ],
  },

  {
    id: 'codr1-lesson3', name: 'Frequency Counts', unit: 1, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr1-lesson3-q1', type: 'multiple_choice',
        question: 'What is the most Pythonic way to count character frequencies in a string?',
        codeSnippet: 'from collections import Counter\n\nfreq = Counter("aabbc")\n# freq → Counter({\'a\': 2, \'b\': 2, \'c\': 1})\nfreq[\'a\']  # → 2',
        codeLanguage: 'python',
        options: ['Sorting the string first', 'Using a nested loop', 'Using collections.Counter', 'Using a set'],
        correct: 2,
        explanationShort: 'Counter("aabbc") gives Counter({\'a\': 2, \'b\': 2, \'c\': 1}) in one line. It\'s built for exactly this.',
        tags: ['frequency', 'counter', 'python'],
      },
      {
        id: 'codr1-lesson3-q2', type: 'multiple_choice',
        question: 'What is the time complexity of building a frequency map for n elements?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
        correct: 2,
        explanationShort: 'Each element is visited once, and each hash map insertion is O(1) average — total O(n).',
        tags: ['frequency', 'complexity'],
      },
      {
        id: 'codr1-lesson3-q3', type: 'multiple_choice',
        question: 'Two strings are anagrams if they have identical character frequencies. What\'s the fastest check?',
        options: [
          'Sort both strings and compare — O(n log n)',
          'Compare their frequency maps — O(n)',
          'Check if one is a substring of the other',
          'Compare their lengths only',
        ],
        correct: 1,
        explanationShort: 'Building two frequency maps is O(n). Sorting is O(n log n). For interviews, both work but the map approach is faster.',
        tags: ['frequency', 'anagram', 'complexity'],
      },
      {
        id: 'codr1-lesson3-q4', type: 'multiple_choice',
        question: 'You want to find the element that appears most frequently. What data structure helps most?',
        options: [
          'A sorted list',
          'A stack',
          'A hash map storing element → frequency',
          'A binary search tree',
        ],
        correct: 2,
        explanationShort: 'Build a frequency map in O(n), then scan values for the max in O(n). Or use Counter.most_common(1) directly.',
        tags: ['frequency', 'hash_map'],
      },
    ],
  },

  {
    id: 'codr1-lesson4', name: 'Prefix Sums', unit: 1, market: 'shared', xpReward: 30,
    questions: [
      {
        id: 'codr1-lesson4-q1', type: 'multiple_choice',
        question: 'For nums = [1, 2, 3, 4], prefix[i] = sum of nums[0..i]. What is prefix[2]?',
        options: ['2', '3', '6', '10'],
        correct: 2,
        explanationShort: 'prefix[2] = nums[0] + nums[1] + nums[2] = 1 + 2 + 3 = 6.',
        tags: ['prefix_sum', 'arrays'],
      },
      {
        id: 'codr1-lesson4-q2', type: 'multiple_choice',
        question: 'With a prefix sum array built, what is the time complexity to find the sum of any subarray?',
        options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
        correct: 2,
        explanationShort: 'sum(l, r) = prefix[r] - prefix[l-1]. Two array lookups and one subtraction — O(1).',
        tags: ['prefix_sum', 'complexity'],
      },
      {
        id: 'codr1-lesson4-q3', type: 'multiple_choice',
        question: 'Which problem is NOT a natural fit for prefix sums?',
        options: [
          'Range sum queries on a fixed array',
          'Finding subarrays with a target sum',
          'Counting prefix occurrences',
          'Finding the maximum element in an array',
        ],
        correct: 3,
        explanationShort: 'Max element requires comparing values, not summing them. Prefix sums are about cumulative totals.',
        tags: ['prefix_sum', 'arrays'],
      },
      {
        id: 'codr1-lesson4-q4', type: 'multiple_choice',
        question: 'What is the space complexity of a prefix sum array for n elements?',
        options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'],
        correct: 2,
        explanationShort: 'You store one prefix value per element — n values total, so O(n) space.',
        tags: ['prefix_sum', 'complexity'],
      },
    ],
  },

  {
    id: 'codr1-quiz', name: 'Unit 1 Quiz', unit: 1, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr1-quiz-q1', type: 'multiple_choice',
        question: 'You need to find if any subarray sums to zero. Which data structure pairs with prefix sums here?',
        options: ['A stack', 'A queue', 'A hash set', 'A sorted array'],
        correct: 2,
        explanationShort: 'If prefix[i] == prefix[j], then the subarray between them sums to zero. A set checks prefix existence in O(1).',
        tags: ['prefix_sum', 'hash_set'],
      },
      {
        id: 'codr1-quiz-q2', type: 'multiple_choice',
        question: 'What is the WORST-case time complexity of hash map lookup?',
        options: ['O(1) always', 'O(log n)', 'O(n) — when many keys collide to the same bucket', 'O(n log n)'],
        correct: 2,
        explanationShort: 'All keys hashing to one bucket degrades to a linked list search — O(n). Good hash functions make this extremely rare.',
        tags: ['hash_map', 'complexity'],
      },
      {
        id: 'codr1-quiz-q3', type: 'multiple_choice',
        question: 'In the hash map Two Sum solution, why don\'t we add the current element before checking for its complement?',
        options: [
          'The problem says elements must be distinct',
          'Checking first prevents pairing an element with itself',
          'We use a set, which removes duplicates automatically',
          'We sort the array first so duplicates are handled',
        ],
        correct: 1,
        explanationShort: 'If we add then check, an element could match itself (e.g. target=4, num=2 would find itself). Check first, then add.',
        tags: ['two_sum', 'hash_map'],
      },
      {
        id: 'codr1-quiz-q4', type: 'multiple_choice',
        question: 'A frequency map shows {\'a\': 3, \'b\': 2, \'c\': 1}. What is being counted?',
        options: [
          'The ASCII values of each character',
          'The positions of each character in the string',
          'How many times each character appears',
          'The unique characters in alphabetical order',
        ],
        correct: 2,
        explanationShort: '\'a\' appears 3 times, \'b\' appears 2 times, \'c\' appears once. This is a frequency/histogram map.',
        tags: ['frequency', 'hash_map'],
      },
      {
        id: 'codr1-quiz-q5', type: 'multiple_choice',
        question: 'You have 1000 range sum queries on a fixed array. Most efficient approach?',
        options: [
          'Brute force — sum the range each time: O(n) per query',
          'Sort the array then binary search',
          'Build a prefix sum array once, answer each query in O(1)',
          'Use a hash map to store all possible sums',
        ],
        correct: 2,
        explanationShort: 'O(n) build + O(1) per query = O(n + q) total. Brute force is O(n·q). The prefix array pays for itself after the first few queries.',
        tags: ['prefix_sum', 'complexity'],
      },
    ],
  },

  // ─── UNIT 2: Two Pointers & Sliding Window ───────────────────────────────────

  {
    id: 'codr2-lesson1', name: 'Two Pointers: Opposite Ends', unit: 2, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr2-lesson1-q1', type: 'multiple_choice',
        question: 'In the two-pointer technique on a sorted array, where do the pointers typically start?',
        arrayData: {
          title: 'SORTED ARRAY — initial pointer positions',
          elements: [
            { value: 2,  highlight: 'primary',   pointer: 'left'  },
            { value: 7,  highlight: 'inactive' },
            { value: 11, highlight: 'inactive' },
            { value: 15, highlight: 'secondary', pointer: 'right' },
          ],
        },
        options: ['Both at index 0', 'One at the start, one at the end', 'Both at the middle', 'One at the start, one at the middle'],
        correct: 1,
        explanationShort: 'Opposite-end pointers work because the sorted array lets you decide which pointer to move based on the current sum vs target.',
        tags: ['two_pointers', 'arrays'],
      },
      {
        id: 'codr2-lesson1-q2', type: 'multiple_choice',
        question: 'Checking if a string is a palindrome using two pointers — what is the time complexity?',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'],
        correct: 2,
        explanationShort: 'Each character is visited at most once as the pointers move toward the centre — O(n).',
        tags: ['two_pointers', 'strings', 'complexity'],
      },
      {
        id: 'codr2-lesson1-q3', type: 'multiple_choice',
        question: 'In the sorted Two Sum problem with two pointers, when do you move the left pointer right?',
        arrayData: {
          title: 'CURRENT STATE — target = 20, sum = 2 + 15 = 17',
          elements: [
            { value: 2,  highlight: 'primary',   pointer: 'left'  },
            { value: 7,  highlight: 'inactive' },
            { value: 11, highlight: 'inactive' },
            { value: 15, highlight: 'secondary', pointer: 'right' },
          ],
        },
        options: [
          'When the sum equals the target',
          'When the sum is greater than the target',
          'When the sum is less than the target',
          'Always after each step',
        ],
        correct: 2,
        explanationShort: 'Sum < target means we need a larger value — move left pointer right to increase the sum.',
        tags: ['two_pointers', 'two_sum'],
      },
      {
        id: 'codr2-lesson1-q4', type: 'multiple_choice',
        question: 'The main advantage of the two-pointer approach over brute force for sorted arrays:',
        options: [
          'Uses less memory',
          'Reduces O(n²) brute force to O(n) by eliminating redundant pair checks',
          'Only works on sorted arrays — a disadvantage',
          'Handles duplicates better than a hash map',
        ],
        correct: 1,
        explanationShort: 'Each pointer moves at most n steps total — O(n). Brute force checks all pairs — O(n²).',
        tags: ['two_pointers', 'complexity'],
      },
    ],
  },

  {
    id: 'codr2-lesson2', name: 'Two Pointers: Fast & Slow', unit: 2, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr2-lesson2-q1', type: 'multiple_choice',
        question: "Floyd's cycle detection uses fast and slow pointers. How fast does each move?",
        arrayData: {
          title: 'AFTER 1 STEP — linked list [1→2→3→4→5]',
          elements: [
            { value: 1, highlight: 'inactive' },
            { value: 2, highlight: 'primary',   pointer: 'slow' },
            { value: 3, highlight: 'secondary', pointer: 'fast' },
            { value: 4, highlight: 'inactive' },
            { value: 5, highlight: 'inactive' },
          ],
        },
        options: [
          'Both move 1 step at a time',
          'Slow moves 1 step, fast moves 2 steps',
          'Slow moves 2 steps, fast moves 3 steps',
          'Both move 2 steps at a time',
        ],
        correct: 1,
        explanationShort: 'Fast moves twice as quickly. If a cycle exists, fast eventually laps slow — they\'re guaranteed to meet.',
        tags: ['fast_slow', 'linked_list', 'cycle'],
      },
      {
        id: 'codr2-lesson2-q2', type: 'multiple_choice',
        question: 'If there is NO cycle in a linked list, what happens to the fast pointer?',
        options: [
          'It meets the slow pointer at the head',
          'It reaches null or null.next',
          'It wraps back to the head',
          'It stays at the middle node',
        ],
        correct: 1,
        explanationShort: 'Without a cycle, the fast pointer falls off the end — it hits null (even length) or null.next (odd length).',
        tags: ['fast_slow', 'linked_list', 'cycle'],
      },
      {
        id: 'codr2-lesson2-q3', type: 'multiple_choice',
        question: 'To find the middle of a linked list with fast/slow pointers, when has slow reached the middle?',
        options: [
          'When fast has moved n/2 steps',
          'When fast reaches the end of the list',
          'When slow and fast are equidistant from the head',
          'After exactly n iterations',
        ],
        correct: 1,
        explanationShort: 'Fast moves 2 steps per slow\'s 1. When fast can\'t move further, slow is at the midpoint.',
        tags: ['fast_slow', 'linked_list'],
      },
      {
        id: 'codr2-lesson2-q4', type: 'multiple_choice',
        question: 'Which problem is NOT naturally solved by the fast/slow pointer pattern?',
        options: [
          'Detecting a cycle in a linked list',
          'Finding the middle of a linked list',
          'Detecting a duplicate number (cycle in an implicit linked list)',
          'Merging two sorted linked lists',
        ],
        correct: 3,
        explanationShort: 'Merging sorted lists uses a comparison pointer, not a speed difference. It\'s a different two-pointer variant.',
        tags: ['fast_slow', 'linked_list'],
      },
    ],
  },

  {
    id: 'codr2-lesson3', name: 'Fixed-Size Sliding Window', unit: 2, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr2-lesson3-q1', type: 'multiple_choice',
        question: 'How many fixed-size windows of size k exist in an array of n elements?',
        options: ['n - k', 'n - k + 1', 'k', 'n / k'],
        correct: 1,
        explanationShort: 'Windows start at index 0, 1, …, n-k. That\'s n-k+1 windows total.',
        tags: ['sliding_window', 'fixed'],
      },
      {
        id: 'codr2-lesson3-q2', type: 'multiple_choice',
        question: 'Time complexity of finding the maximum sum of a subarray of size k using sliding window?',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(k)'],
        correct: 2,
        explanationShort: 'One pass: compute the first window, then slide — add one element, remove one. O(n) total.',
        tags: ['sliding_window', 'complexity'],
      },
      {
        id: 'codr2-lesson3-q3', type: 'multiple_choice',
        question: 'When sliding a window of size k one step right, what two operations update the sum?',
        arrayData: {
          title: 'k = 3 — sliding one step right',
          elements: [
            { value: 4, highlight: 'secondary', pointer: 'leave' },
            { value: 2, highlight: 'window' },
            { value: 1, highlight: 'window' },
            { value: 7, highlight: 'window' },
            { value: 8, highlight: 'primary',   pointer: 'enter' },
            { value: 2, highlight: 'inactive' },
          ],
        },
        options: [
          'Recompute the entire window sum from scratch',
          'Add the incoming element, subtract the outgoing element',
          'Sort the new window',
          'Reset the sum and recount from the start',
        ],
        correct: 1,
        explanationShort: 'windowSum += nums[right] - nums[right - k]. Two O(1) operations per slide instead of O(k) recomputation.',
        tags: ['sliding_window', 'fixed'],
      },
      {
        id: 'codr2-lesson3-q4', type: 'multiple_choice',
        question: 'The key insight that makes sliding window more efficient than brute force:',
        options: [
          'It uses recursion to divide the problem',
          'It reuses the previous window\'s computation — only process the change',
          'It only works when elements are positive',
          'It reduces space complexity to O(1)',
        ],
        correct: 1,
        explanationShort: 'Adjacent windows share k-1 elements. Sliding reuses that overlap instead of recomputing from scratch.',
        tags: ['sliding_window', 'fundamentals'],
      },
      {
        id: 'codr2-lesson3-q5', type: 'multiple_choice',
        question: 'Maximum sum subarray of size k over an array — sliding window runs in:',
        options: [
          'O(n²) — nested loops checking all subarrays',
          'O(n·k) — recompute each window',
          'O(n) — one pass, add/subtract one element per step',
          'O(k log k) — sort each window',
        ],
        correct: 2,
        explanationShort: 'Each element is added once and removed once over the full pass — 2n operations total, so O(n).',
        tags: ['sliding_window', 'complexity'],
      },
    ],
  },

  {
    id: 'codr2-lesson4', name: 'Variable-Size Sliding Window', unit: 2, market: 'shared', xpReward: 30,
    questions: [
      {
        id: 'codr2-lesson4-q1', type: 'multiple_choice',
        question: 'In a variable-size sliding window, when do you expand the window (move right pointer)?',
        options: [
          'When the window violates the constraint',
          'When you want to explore a potentially larger valid window',
          'At every step regardless of constraint',
          'Only when the window is empty',
        ],
        correct: 1,
        explanationShort: 'Always extend right to include more elements. Contract left only when the window becomes invalid.',
        tags: ['sliding_window', 'variable'],
      },
      {
        id: 'codr2-lesson4-q2', type: 'multiple_choice',
        question: 'When do you shrink (move left pointer) in a variable-size sliding window?',
        options: [
          'When the window satisfies the constraint',
          'When the window violates the constraint',
          'After every expansion',
          'When the right pointer reaches the end',
        ],
        correct: 1,
        explanationShort: 'Keep shrinking from the left until the window is valid again, then continue expanding right.',
        tags: ['sliding_window', 'variable'],
      },
      {
        id: 'codr2-lesson4-q3', type: 'multiple_choice',
        question: '"Longest substring without repeating characters" — what tracks window validity?',
        options: [
          'A sorted list of characters',
          'A queue of characters',
          'A hash set of characters currently in the window',
          'A prefix sum array',
        ],
        correct: 2,
        explanationShort: 'A set gives O(1) duplicate checks. When a duplicate is found, shrink left until it\'s gone.',
        tags: ['sliding_window', 'hash_set', 'strings'],
      },
      {
        id: 'codr2-lesson4-q4', type: 'multiple_choice',
        question: 'Time complexity of "longest substring without repeating characters" with sliding window:',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(26)'],
        correct: 2,
        explanationShort: 'Each character is added to and removed from the set at most once — at most 2n operations, so O(n).',
        tags: ['sliding_window', 'complexity'],
      },
      {
        id: 'codr2-lesson4-q5', type: 'multiple_choice',
        question: '"Minimum window substring containing all target chars" — the window:',
        options: [
          'Only shrinks — start large and contract',
          'Both expands (right pointer) and contracts (left pointer) to find the minimum valid window',
          'Must be exactly the length of the target',
          'Stays fixed once it contains all target characters',
        ],
        correct: 1,
        explanationShort: 'Expand right until valid, record as candidate answer, then shrink left to find a smaller valid window.',
        tags: ['sliding_window', 'variable'],
      },
    ],
  },

  {
    id: 'codr2-quiz', name: 'Unit 2 Quiz', unit: 2, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr2-quiz-q1', type: 'multiple_choice',
        question: 'Which problem is best solved with opposite-ends two pointers?',
        options: [
          'Find the k-th largest element',
          'Detect a cycle in a linked list',
          'Find two numbers in a SORTED array that sum to a target',
          'Find the longest substring without repeating characters',
        ],
        correct: 2,
        explanationShort: 'Sorted array + two ends = classic two-pointer. Cycle detection → fast/slow. Longest substring → sliding window.',
        tags: ['two_pointers', 'pattern_recognition'],
      },
      {
        id: 'codr2-quiz-q2', type: 'multiple_choice',
        question: 'Floyd\'s cycle detection: slow moves 1, fast moves 2. If they meet, what is proven?',
        options: [
          'The list has an even number of nodes',
          'There is a cycle in the list',
          'The fast pointer wrapped around the beginning',
          'The list has an odd number of nodes',
        ],
        correct: 1,
        explanationShort: 'In a cycle, fast eventually laps slow. If they meet, a cycle must exist. If fast reaches null, no cycle.',
        tags: ['fast_slow', 'cycle'],
      },
      {
        id: 'codr2-quiz-q3', type: 'multiple_choice',
        question: 'What makes a problem require a VARIABLE window rather than a fixed one?',
        options: [
          'The array contains duplicates',
          'The optimal window size is unknown and depends on a dynamic constraint',
          'The array is unsorted',
          'The problem asks for a sum',
        ],
        correct: 1,
        explanationShort: '"Maximum sum of k elements" → fixed window (k is given). "Longest valid substring" → variable (size is what you\'re finding).',
        tags: ['sliding_window', 'pattern_recognition'],
      },
      {
        id: 'codr2-quiz-q4', type: 'multiple_choice',
        question: 'A fixed window of size 3 slides over [1,3,-1,-3,5,3,6,7]. Total number of windows?',
        options: ['3', '5', '6', '8'],
        correct: 2,
        explanationShort: 'n=8, k=3. Windows = n - k + 1 = 8 - 3 + 1 = 6.',
        tags: ['sliding_window', 'fixed'],
      },
      {
        id: 'codr2-quiz-q5', type: 'multiple_choice',
        question: 'Time complexity of fast/slow pointer cycle detection on a linked list of n nodes?',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'],
        correct: 2,
        explanationShort: 'At most 2n steps before fast reaches null or the pointers meet inside the cycle — O(n).',
        tags: ['fast_slow', 'complexity'],
      },
      {
        id: 'codr2-quiz-q6', type: 'multiple_choice',
        question: 'After shrinking the left pointer in a variable window (removing char c), what must you do?',
        options: [
          'Add c to the result',
          'Remove c from the tracking set/map',
          'Decrement the right pointer',
          'Reset the entire window',
        ],
        correct: 1,
        explanationShort: 'The window\'s data structure must stay in sync with its boundaries. Removing left means removing its character from the set.',
        tags: ['sliding_window', 'variable'],
      },
    ],
  },

  // ─── UNIT 3: Stack & Queue ───────────────────────────────────────────────────

  {
    id: 'codr3-lesson1', name: 'Stack: LIFO & Use Cases', unit: 3, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr3-lesson1-q1', type: 'multiple_choice',
        question: 'What does LIFO stand for?',
        options: ['Last Input First Output', 'Last In First Out', 'Linear Indexed Forward Offset', 'Lowest Index First Operation'],
        correct: 1,
        explanationShort: 'Last In First Out — the most recently added element is the first to be removed. Like a stack of plates.',
        tags: ['stack', 'fundamentals'],
      },
      {
        id: 'codr3-lesson1-q2', type: 'multiple_choice',
        question: 'Which Python data structure efficiently acts as a stack?',
        options: [
          'dict — O(1) access by key',
          'list — append() and pop() are O(1) at the end',
          'tuple — immutable sequence',
          'set — O(1) membership check',
        ],
        correct: 1,
        explanationShort: 'list.append() and list.pop() (no index) both operate on the tail in O(1). Never pop from the front — that\'s O(n).',
        tags: ['stack', 'python'],
      },
      {
        id: 'codr3-lesson1-q3', type: 'multiple_choice',
        question: 'Which of these is NOT a natural use case for a stack?',
        options: [
          'Tracking function call frames (the call stack)',
          'Undo/redo operations in a text editor',
          'Evaluating mathematical expressions with operator precedence',
          'Processing requests in the order they arrive (FIFO)',
        ],
        correct: 3,
        explanationShort: 'FIFO processing is a queue, not a stack. The call stack, undo, and expression evaluation all rely on LIFO.',
        tags: ['stack', 'use_cases'],
      },
      {
        id: 'codr3-lesson1-q4', type: 'multiple_choice',
        question: 'Time complexity of push and pop operations on a stack:',
        options: ['O(n) — must shift elements', 'O(log n)', 'O(1)', 'O(n²)'],
        correct: 2,
        explanationShort: 'Push and pop always touch only the top element — O(1). This is what makes a stack useful.',
        tags: ['stack', 'complexity'],
      },
    ],
  },

  {
    id: 'codr3-lesson2', name: 'Monotonic Stack', unit: 3, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr3-lesson2-q1', type: 'multiple_choice',
        question: 'What property defines a monotonic stack?',
        options: [
          'All elements are unique',
          'Elements are maintained in strictly increasing or decreasing order',
          'The stack never holds more than k elements',
          'Elements are sorted before being pushed',
        ],
        correct: 1,
        explanationShort: 'We pop elements that violate the monotonic property before pushing the new one, maintaining the order invariant.',
        tags: ['monotonic_stack', 'fundamentals'],
      },
      {
        id: 'codr3-lesson2-q2', type: 'multiple_choice',
        question: 'Finding "Next Greater Element" for each array element — what does the stack hold?',
        options: [
          'The maximum element seen so far',
          'Elements (or their indices) waiting to find their next greater element',
          'All elements in sorted order',
          'Only the indices of processed elements',
        ],
        correct: 1,
        explanationShort: 'Elements sit on the stack unresolved. When a larger element arrives, it resolves everything smaller below it.',
        tags: ['monotonic_stack', 'next_greater'],
      },
      {
        id: 'codr3-lesson2-q3', type: 'multiple_choice',
        question: 'Time complexity of Next Greater Element for all n elements using a monotonic stack?',
        options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(n·k)'],
        correct: 2,
        explanationShort: 'Each element is pushed once and popped at most once — at most 2n total operations, so O(n).',
        tags: ['monotonic_stack', 'complexity'],
      },
      {
        id: 'codr3-lesson2-q4', type: 'multiple_choice',
        question: 'In a monotonically increasing stack (top is largest), when do you pop?',
        options: [
          'When the incoming element is larger than the top',
          'When the incoming element is smaller than the top',
          'After every push',
          'When the stack reaches a fixed size',
        ],
        correct: 1,
        explanationShort: 'To maintain increasing order (bottom → top), pop anything larger than the incoming element.',
        tags: ['monotonic_stack', 'fundamentals'],
      },
      {
        id: 'codr3-lesson2-q5', type: 'multiple_choice',
        question: '"Largest Rectangle in Histogram" uses a monotonic stack. What does the stack track?',
        options: [
          'Heights in sorted order',
          'Indices of bars in non-decreasing height order',
          'The maximum height seen so far',
          'The cumulative area at each position',
        ],
        correct: 1,
        explanationShort: 'We store indices of bars in increasing height. When a shorter bar arrives, we compute rectangle area for each popped bar.',
        tags: ['monotonic_stack', 'histogram'],
      },
    ],
  },

  {
    id: 'codr3-lesson3', name: 'Queue & Deque', unit: 3, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr3-lesson3-q1', type: 'multiple_choice',
        question: 'What does FIFO stand for and which data structure implements it?',
        options: ['First In First Out — Queue', 'First In First Out — Stack', 'First Input Final Output — Queue', 'Forward Index Forward Output — Deque'],
        correct: 0,
        explanationShort: 'First In First Out — the element waiting longest is served first. This is a queue, like a checkout line.',
        tags: ['queue', 'fundamentals'],
      },
      {
        id: 'codr3-lesson3-q2', type: 'multiple_choice',
        question: 'Why use collections.deque instead of a list for a queue in Python?',
        options: [
          'Deque supports more methods than list',
          'Deque\'s popleft() is O(1); list\'s pop(0) is O(n)',
          'Deque uses less memory',
          'Deque is automatically sorted',
        ],
        correct: 1,
        explanationShort: 'list.pop(0) shifts every remaining element — O(n). deque is a doubly-linked structure with O(1) at both ends.',
        tags: ['queue', 'deque', 'python'],
      },
      {
        id: 'codr3-lesson3-q3', type: 'multiple_choice',
        question: 'Which algorithm uses a queue as its core data structure?',
        options: ['DFS — depth-first search', 'Binary search', 'BFS — breadth-first search', 'Merge sort'],
        correct: 2,
        explanationShort: 'BFS explores neighbours level by level. The queue ensures nodes are processed in the order they were discovered.',
        tags: ['queue', 'bfs'],
      },
      {
        id: 'codr3-lesson3-q4', type: 'multiple_choice',
        question: 'Time complexity of deque.appendleft() and deque.popleft() in Python:',
        options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
        correct: 2,
        explanationShort: 'Both ends of a deque are O(1). This is the whole point — it\'s a double-ended queue.',
        tags: ['deque', 'complexity'],
      },
    ],
  },

  {
    id: 'codr3-lesson4', name: 'Valid Parentheses Pattern', unit: 3, market: 'shared', xpReward: 25,
    questions: [
      {
        id: 'codr3-lesson4-q1', type: 'multiple_choice',
        question: 'Checking valid parentheses: you push opening brackets. When do you pop?',
        options: [
          'At the end of the string',
          'When you see another opening bracket',
          'When you see a closing bracket — pop and check if it matches',
          'When the stack is half full',
        ],
        correct: 2,
        explanationShort: 'Each closing bracket must match the most recently opened one. The stack gives you the most recent — pop and verify.',
        tags: ['stack', 'parentheses'],
      },
      {
        id: 'codr3-lesson4-q2', type: 'multiple_choice',
        question: 'After processing "(()())", what should the stack contain?',
        options: [
          'All the opening brackets',
          'Nothing — the stack should be empty',
          'All the closing brackets',
          'One unmatched bracket',
        ],
        correct: 1,
        explanationShort: 'Every opening bracket was matched and popped. Empty stack = all brackets matched = valid.',
        tags: ['stack', 'parentheses'],
      },
      {
        id: 'codr3-lesson4-q3', type: 'multiple_choice',
        question: 'Why does this problem require a stack rather than just a counter?',
        options: [
          'A counter is slower',
          'A counter can\'t distinguish between different bracket types — \'(\', \'[\', \'{\'',
          'A stack uses less memory',
          'The counter overflows for long inputs',
        ],
        correct: 1,
        explanationShort: 'A counter of +1/-1 would accept "([)]" as valid. A stack catches mismatched types because it preserves order.',
        tags: ['stack', 'parentheses'],
      },
      {
        id: 'codr3-lesson4-q4', type: 'multiple_choice',
        question: 'Time and space complexity of the stack-based Valid Parentheses solution:',
        options: ['O(n²) time, O(1) space', 'O(n) time, O(n) space', 'O(n log n) time, O(log n) space', 'O(1) time, O(n) space'],
        correct: 1,
        explanationShort: 'One pass through n characters — O(n) time. The stack holds at most n/2 opening brackets — O(n) space.',
        tags: ['stack', 'complexity'],
      },
    ],
  },

  {
    id: 'codr3-quiz', name: 'Unit 3 Quiz', unit: 3, market: 'shared', xpReward: 50,
    questions: [
      {
        id: 'codr3-quiz-q1', type: 'multiple_choice',
        question: 'Which data structure to reach for when a problem involves "undoing" or "backtracking"?',
        options: ['Queue', 'Stack', 'Hash map', 'Prefix sum array'],
        correct: 1,
        explanationShort: 'Undo/backtrack always reverses the most recent action — exactly LIFO. Stack is the natural choice.',
        tags: ['stack', 'pattern_recognition'],
      },
      {
        id: 'codr3-quiz-q2', type: 'multiple_choice',
        question: 'BFS on a graph with n nodes and e edges — time complexity:',
        options: ['O(n²)', 'O(n log n)', 'O(n + e)', 'O(e²)'],
        correct: 2,
        explanationShort: 'Each node is enqueued once (O(n)) and each edge is examined once (O(e)) — total O(n + e).',
        tags: ['queue', 'bfs', 'complexity'],
      },
      {
        id: 'codr3-quiz-q3', type: 'multiple_choice',
        question: 'Monotonic stack for Next Greater Element: what happens to elements that never find a greater element?',
        options: [
          'They are removed immediately on push',
          'They remain in the stack when processing ends',
          'They are assigned -1 during processing',
          'They cause a stack overflow',
        ],
        correct: 1,
        explanationShort: 'Elements without a greater element are never popped. Check the remaining stack at the end — they get answer -1 (or ∞).',
        tags: ['monotonic_stack', 'next_greater'],
      },
      {
        id: 'codr3-quiz-q4', type: 'multiple_choice',
        question: 'You need to access both the most recently added AND the least recently added element efficiently. Which structure?',
        options: ['Stack — only the top', 'Queue — only the front', 'Deque', 'Priority queue'],
        correct: 2,
        explanationShort: 'Deque (double-ended queue) gives O(1) access at both ends. Stack and queue only expose one end.',
        tags: ['deque', 'pattern_recognition'],
      },
      {
        id: 'codr3-quiz-q5', type: 'multiple_choice',
        question: 'The string is "(]". What does the Valid Parentheses algorithm return?',
        options: [
          'True — there is one opening and one closing bracket',
          'False — \'(\' is on the stack when \']\' arrives, and they don\'t match',
          'True — all brackets are closed',
          'Error — mixed bracket types are invalid input',
        ],
        correct: 1,
        explanationShort: 'Push \'(\'. See \']\'. Pop top — it\'s \'(\', not \'[\'. Mismatch → return False immediately.',
        tags: ['stack', 'parentheses'],
      },
    ],
  },
];

export default CODR_LESSONS;
